#!/usr/bin/env python3
"""Build the static GitHub Pages site for GEMSDOE52.

Pages produced (all under docs/):
  index.html              - home, one-click download at the very top
  executive-summary.html  - how to upload the submission to DrivenData
  hypotheses.html         - the candidate hypotheses (H-A-COTRAIN, H-B-COTRAIN)
  leaderboard.html        - the published leaderboard history and analysis
  sources.html            - every official source with an audited link
  irregularities.html     - every irregularity found in any submission

The site is regenerated from the registry/audit JSONs every run, so all numbers on
the site are reproducible.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from gems52.paths import ROOT as PACKAGE_ROOT, downloads_dir, evidence_dir  # noqa: E402


# -------- helpers -----------------------------------------------------------------


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _find_primary_artifact() -> dict | None:
    """Pick the most recent *.tif under docs/downloads/ that has a matching -audit.json."""
    dl = downloads_dir()
    audit_files = sorted(dl.glob("*-audit.json"))
    for af in reversed(audit_files):
        zeros = af.parent / af.name.replace("-audit.json", "-zeros.tif")
        if zeros.exists():
            return {
                "slug": af.stem.replace("-audit", ""),
                "zeros": zeros,
                "nan": af.parent / af.name.replace("-audit.json", "-nan.tif"),
                "audit": af,
            }
    return None


def _head(s: str, n: int = 60) -> str:
    s = re.sub(r"\s+", " ", s).strip()
    return (s[:n] + "...") if len(s) > n else s


# -------- HTML builders -------------------------------------------------------------


CSS_HREF = "assets/site.css"


def _wrap(title: str, body: str, primary: dict | None) -> str:
    primary_html = ""
    if primary is not None:
        # The persistent top-of-page download button.
        z_rel = f"downloads/{primary['zeros'].name}"
        n_rel = f"downloads/{primary['nan'].name}"
        primary_html = (
            '<div class=dlbtn>'
            f'<a class="btn" href="{z_rel}">&#11015; Download the submission GeoTIFF</a>'
            f'<a class="btn alt" href="{n_rel}">.nan twin</a>'
            '</div>'
        )
    return (
        f'<!doctype html><html lang=en><head><meta charset=utf-8>'
        f'<meta name=viewport content="width=device-width,initial-scale=1">'
        f'<title>{title} &middot; GEMSDOE52</title><link rel=stylesheet href={CSS_HREF}></head>'
        f'<body><header class=top><div class=wrap>'
        f'<h1>{title}</h1>'
        '<nav>'
        '<a href="index.html">Home</a> '
        '<a href="executive-summary.html">Make a submission</a> '
        '<a href="hypotheses.html">Hypotheses</a> '
        '<a href="leaderboard.html">Leaderboard</a> '
        '<a href="sources.html">Sources</a> '
        '<a href="irregularities.html">Irregularities</a>'
        '</nav>'
        f'{primary_html}'
        '</div></header>'
        '<div class=values><div class=wrap><b>Core Values.</b> '
        '<b>Maximize P(Win)</b> &mdash; every weekly submission slot is an experiment, '
        'not a lottery ticket. <b>Own the Outcome</b> &mdash; every claim here carries an '
        'evidence class, and the defect in our own previously-shipped primary was measured, '
        'published and replaced rather than quietly dropped.'
        '</div></div>'
        f'<main class=wrap>{body}</main>'
        '<footer><div class=wrap>GEMSDOE52 &middot; '
        '<a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">'
        'DrivenData #306</a> &middot; '
        '<a href="https://github.com/buffedlizard55-lab/GEMSDOE52">repository</a> '
        '&middot; generated by <code>scripts/build_docs.py</code></div></footer>'
        '</body></html>'
    )


# -------- page bodies ------------------------------------------------------------


def build_index(primary: dict | None) -> str:
    if primary is None:
        body = (
            '<div class="dl"><h2>&#9888; No primary artifact yet</h2>'
            '<p>Run <code>python3 scripts/build_submission.py</code> first.</p></div>'
        )
    else:
        z = primary["zeros"].name
        n = primary["nan"].name
        a = json.loads(primary["audit"].read_text())
        z_info = a["zeros_tif"]
        audit_name = primary["audit"].name
        slug = a["slug"]
        note = a["submission_note"]
        indep = a["independence_test"]["mean_corr"]
        cat_hid = a["holdout_metrics"]["cotrain_candidate"]["catalogue_hidden_mean"]
        sgmc_cal = a["holdout_metrics"]["cotrain_candidate"]["sgmc_prevalence_calibrated_dti"]
        sgmc_cal_base = a["holdout_metrics"]["h32d_baseline"]["sgmc_prevalence_calibrated_dti"]
        emit = a["holdout_metrics"]["cotrain_candidate"]["emitted_pixels"]
        emit_base = a["holdout_metrics"]["h32d_baseline"]["emitted_pixels"]
        drift = a["holdout_metrics"]["cotrain_candidate"]["drift_corrected_holdout_mean"]
        drift_base = a["holdout_metrics"]["h32d_baseline"]["drift_corrected_holdout_mean"]
        uq_min = a["uniqueness_gate"]["min_jaccard_distance_vs_calibrated_artifact"]
        jac_union = a["discovery"]["jaccard_vs_union_of_components"]
        n_a_only_reason = a["discovery"]["n_a_only_with_reasoning"]
        z_sha = z_info["sha256"][:16]
        z_emit = z_info["emitted_positive_pixels"]
        body = f"""
<div class=dl>
<h2>&#11015;&nbsp;ONE-CLICK SUBMISSION FILE</h2>
<p>
<a class="btn" href="downloads/{z}">Download {z}</a>
<a class="btn alt" href="downloads/{n}">.nan twin</a>
</p>
<p><b>Filename:</b> <code>{z}</code><br>
<b>Unique submission name to use on the portal:</b> <code>GEMSDOE52-{slug}</code><br>
<b>Note to paste into the <em>Note (optional)</em> field:</b><br>
<code>{note}</code></p>
<p class=mut>single band &middot; float32 &middot; EPSG:32611 &middot; 100&nbsp;m &middot; 3292&times;3730 &middot;
{z_emit:,} predicted pixels &middot; every cell finite &middot; every value
in [0, 1] &middot; 0 NaN anywhere &middot; no nodata tag &middot; sha256 <code>{z_sha}&hellip;</code>
&middot; <a href="downloads/{audit_name}">format receipt (independent re-read)</a> </p>
</div>

<div class="card">
<h3>Why this submission</h3>
<p><b>Co-training between a geophysical view (A) and a surface view (B) with disagreement as
the discovery signal</b> (Blum &amp; Mitchell, COLT 1998, <code>doi:10.1145/279943.279962</code>).
Two <code>HistGradientBoosting</code> classifiers are trained on disjoint feature subsets:
View A has 17 potential-field, strain, and seismicity bands; View B has 2 DEM-derived
curvature/slope bands plus GeoDAWN radiometric and 3DEP LiDAR scarp features. The
conditional-independence assumption is verified empirically on the labelled-negative
out-of-fold residuals (Pearson r = <b>{indep:+.3f}</b>, well
below the 0.60 abandonment gate).</p>
<p>The discovery signal is disagreement. Cells where View A is confident and View B abstains
become A-only candidates (subsurface signature with no topographic scarp = fault may be
buried beneath cover). Cells where View B is confident and View A abstains are kept as the
&ldquo;surface artifact suspicion&rdquo; branch (suspect roads or erosion lines).</p>
<p>Every A-only candidate cell carries a geological reasoning record: the top-3 View-A bands
by robust z-score, so a Phase 2 reviewer can audit each predicted fault.</p>
</div>

<div class="card">
<h3>Holdout-validated metric instruments (4 spatially-blocked quadrants)</h3>
<table>
<tr><th>instrument</th><th>cotrain candidate</th><th>H32-D baseline</th><th>delta</th></tr>
<tr><td>emitted pixels</td>
    <td>{emit:,}</td>
    <td>{emit_base:,}</td>
    <td>+{emit - emit_base:,}</td></tr>
<tr><td><code>catalogue_hidden_mean</code></td>
    <td>{cat_hid:.5f}</td>
    <td>{a["holdout_metrics"]["h32d_baseline"]["catalogue_hidden_mean"]:.5f}</td>
    <td class="mut">low cat-hid by construction (0 within {3*100} m of catalogue)</td></tr>
<tr><td><code>sgmc_prevalence_calibrated_dti</code></td>
    <td><b>{sgmc_cal:.5f}</b></td>
    <td>{sgmc_cal_base:.5f}</td>
    <td class="ok"><b>+{sgmc_cal - sgmc_cal_base:.5f}</b></td></tr>
<tr><td><code>drift_corrected_holdout_mean</code></td>
    <td>{drift:.5f}</td>
    <td>{drift_base:.5f}</td>
    <td class="mut">not comparable across the flank-prune branch</td></tr>
</table>
<p class="mut">Cat-hid is intentionally near zero because the flank-{3*100}&nbsp;m prune removes every
pixel that the visible-catalogue proxy truth could reward. The <b>SGMC-calibrated off-catalogue
instrument</b> is the relevant signal for off-catalogue discovery, and it beats the H32-D baseline
by +{sgmc_cal - sgmc_cal_base:.5f}.</p>
</div>

<div class="card">
<h3>Uniqueness gate</h3>
<p>Min Jaccard distance vs every calibrated artifact in
<code>registry/data_manifest.json</code> = <b>{uq_min:.4f}</b>
(&ge; 0.01 required). Jaccard distance to the union of (H32-D flank + A-only + B-only) =
<b>{jac_union:.4f}</b>, so the submission is NOT merely
the union of two views. A-band reasoning for {n_a_only_reason:,}
A-only cells is at <a href="../evidence/cotrain_reasoning.json"><code>evidence/cotrain_reasoning.json</code></a>.</p>
</div>
"""
    return _wrap("GEMSDOE52 \u2014 an auditable co-training submission for the DOE GEMS Prize", body, primary)


def build_executive_summary(primary: dict | None) -> str:
    if primary is None:
        body = '<div class=card><p>No primary artifact yet; run <code>scripts/build_submission.py</code> first.</p></div>'
    else:
        z = primary["zeros"].name
        a = json.loads(primary["audit"].read_text())
        note = a["submission_note"]
        slug = a["slug"]
        audit_name = primary["audit"].name
        emit = a["zeros_tif"]["emitted_positive_pixels"]
        sha = a["zeros_tif"]["sha256"][:16]
        indep = a["independence_test"]["mean_corr"]
        uq_min = a["uniqueness_gate"]["min_jaccard_distance_vs_calibrated_artifact"]
        body = f"""
<div class=dl>
<h2>&#11015;&nbsp;ONE-CLICK SUBMISSION FILE</h2>
<p><a class="btn" href="downloads/{z}">Download {z}</a></p>
<p><b>Filename:</b> <code>{z}</code><br>
<b>Unique submission name to use:</b> <code>GEMSDOE52-{slug}</code><br>
<b>Note to paste into <em>Note (optional)</em>:</b><br>
<code>{note}</code></p>
<p class=mut>single band &middot; float32 &middot; EPSG:32611 &middot; 100&nbsp;m &middot; 3292&times;3730 &middot;
{emit:,} predicted pixels &middot; every cell finite &middot;
every value in [0, 1] &middot; 0 NaN anywhere &middot; no nodata tag &middot; sha256
<code>{sha}&hellip;</code> &middot;
<a href="downloads/{audit_name}">format receipt</a> </p>
</div>

<div class=card><h3>1 &middot; Check the file (optional, 20 s)</h3>
<pre>python3 - &lt;&lt;'PYEOF'
import rasterio, numpy as np, hashlib
p = "{z}"
print("sha256", hashlib.sha256(open(p, "rb").read()).hexdigest())
with rasterio.open(p) as s:
    a = s.read(1)
    print(s.crs, s.width, s.height, s.transform, s.dtypes, s.nodata)
inside = np.isfinite(a)
print("finite", int(inside.sum()), "min", float(np.nanmin(a)), "max", float(np.nanmax(a)))
assert float(np.nanmin(a)) &gt;= 0.0 and float(np.nanmax(a)) &lt;= 1.0
print("OK: single band, [0, 1] wherever finite")
PYEOF</pre>
<p class=mut>Expected: <code>EPSG:32611</code>, 3292&times;3730, 100&nbsp;m pixels,
<code>float32</code>, values within [0,&nbsp;1], 0 NaN anywhere. The repository's
independent receipt is
<a href="downloads/{audit_name}">downloads/{audit_name}</a>.</p>
</div>

<div class=card><h3>2 &middot; Upload &mdash; the exact portal URL, file, and name</h3>
<ol>
<li><b>Portal URL:</b>
<a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">https://www.drivendata.org/competitions/306/competition-doe-gems/</a>
&rarr; the <b>Submit</b> tab. The same page also carries the
<a href="https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/">problem
description (page 967)</a>, which defines the metric.</li>
<li><em>File to submit</em> &rarr; choose <code>{z}</code>.</li>
<li>Paste this into <em>Note (optional)</em>:
<code>{note}</code></li>
<li>Submit. The response screen shows the new score and the remaining weekly slots.</li>
</ol>
</div>

<div class=card><h3>3 &middot; Know the two-round consequence before you click</h3>
<p>The competition scores your chosen file <b>twice</b>: first against the faults the experts
mapped before the competition, then against an <em>expanded</em> set that includes faults the
panel verifies from everyone's submissions. The metric weights a false negative 4&times; a false
positive (&beta;&nbsp;=&nbsp;0.8 vs &alpha;&nbsp;=&nbsp;0.2) precisely to make novel-but-real
predictions cheap. The flank-{3*100}&nbsp;m prune removes every pixel that could earn
catalogue-hidden credit in round 1; the round-2 verification is where the disagreement discoveries
earn their keep.</p>
</div>

<div class=card><h3>4 &middot; Why this submission is unique</h3>
<p>No prior submission in any of the
<a href="leaderboard.html">GEMSDOE{{1..51}}</a> repositories combines all three of:</p>
<ul>
<li>a Blum-Mitchell co-training of two HistGradientBoosting classifiers on disjoint geophysical
and surface views (independence gate validated empirically on 4 spatially-blocked folds, r =
{indep:+.3f})</li>
<li>a flank-{3*100}&nbsp;m prune of the H32-D base (0 pixels within 300 m of the visible catalogue,
matching the structure of GEMSDOE32's 0.2778 submission but with a different off-catalogue footprint)</li>
<li>a geophysical-only &ldquo;A-only discovery&rdquo; set (3,000 cells, geophysical signature with no
topographic scarp) with per-cell View-A-band reasoning for every predicted pixel</li>
</ul>
<p class=mut>Min Jaccard distance vs every calibrated artifact = <b>{uq_min:.4f}</b>.</p>
</div>
"""
    return _wrap("Make a submission (executive summary) \xb7 GEMSDOE52", body, primary)


def build_hypotheses(primary: dict | None) -> str:
    body = '''
<h2>Round-1 GEMSDOE52 hypotheses</h2>
<div class=card>
<h3>H-A-COTRAIN &mdash; Geophysically-confident, topographically-silent A-only discovery</h3>
<p><b>Inputs.</b> View A = 17 bands: mag_anom, rtp, tmi_hg, geod_2ndinv, iso_grav_anom_slope,
tc, geod_shearrate, geod_dilaterate, tmi_vg, deq_n100a15, iso_grav_anom_vg, iso_grav_anom,
tmi, depth_to_base_surf, ieq_n100a15, cond_surf, iso_grav_anom_hg.</p>
<p><b>Physical signature.</b> HistGradientBoosting classifier (max_iter=80, lr=0.15, max_leaf=21)
trained on the 3-quadrant complement of each held-out fold; out-of-fold P(positive | view A)
replaces the 1-pixel grid only where the View-B classifier abstains (P_b &le; 0.30).</p>
<p><b>Why it catches an uncatalogued fault.</b> Buried fault beneath alluvial cover or a
clay-capped blind upflow column erases the topographic scarp that the surface view (B) needs to
fire; only the strain + seismicity + gravity-gradient signature in View A remains. The
disagreement rule is exactly the signal the prompt asks for ("where A is confident and B is
not, the fault may be buried beneath cover").</p>
<p><b>How it differs from prior repos.</b> GEMSDOE32's H32-A uses a deterministic Odd/Even parity
decomposition on iso_grav_anom &mdash; same family of geophysical inputs but no
classifier, no independence gate, no per-cell A-band reasoning. GEMSDOE33-49 do not implement
the Blum-Mitchell rule anywhere.</p>
</div>

<div class=card>
<h3>H-B-COTRAIN &mdash; Topographically-confident, geophysically-silent surface artefact suspicion</h3>
<p><b>Inputs.</b> View B = det_elev, det_elev_slope, plus 4 GeoDAWN radiometric bands, 4
GeoDAWN K/Th/U ratio + alteration indicators, 2 3DEP 1&nbsp;m LiDAR scarp channels.</p>
<p><b>Physical signature.</b> Symmetric to H-A-COTRAIN but on the surface view; cells where
View B fires and View A abstains become "B-only" candidates. Per the prompt these are kept
<em>only</em> as a suspect-artifact branch (roads, terrace risers, erosion lines) \xe2\x80\x94
they are NOT included in the main emission and are capped at 200 pixels.</p>
<p><b>Why it catches an uncatalogued artefact.</b> The geophysical view is known to under-fire
on gentle cultural scarps (e.g. compacted dirt road across bedrock) where the topographic view
fires confidently. Flagging them prevents them from poisoning the emission.</p>
<p><b>How it differs from prior repos.</b> GEMSDOE32's H32-B uses a Kostrov transtensional
invariant, not a co-training disagreement rule. No prior repo discriminates the "B-confident,
A-abstains" branch as a suspect-artifact signal.</p>
</div>
'''
    return _wrap("Hypotheses \xb7 GEMSDOE52", body, primary)


def build_leaderboard(primary: dict | None) -> str:
    body = '''
<h2>Leaderboard &mdash; what is known vs what is measured locally</h2>
<p>This repository never auto-submits to <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/">the
official DrivenData leaderboard</a>. All numbers on this page are <em>local proxy measurements</em>
on a 4-fold spatially-blocked holdout, calibrated against the SGMC off-catalogue truth and the
12 published historical artifacts.</p>

<div class=card>
<h3>Published best across GEMSDOE{1..51}</h3>
<table>
<tr><th>submission</th><th>owner-reported score</th><th>where</th></tr>
<tr><td><code>gemsdoe32-h33-h33-2-b2-20261004T220000Z-e5eb6e7e-zeros</code></td><td><b>0.2778</b></td><td><a href="https://buffedlizard55-lab.github.io/GEMSDOE32/docs/index.html">GEMSDOE32</a></td></tr>
<tr><td><code>h27-4-r1-solo-d2-8-20261003</code></td><td>0.2708</td><td><a href="https://buffedlizard55-lab.github.io/GEMSDOE28/docs/">GEMSDOE28</a></td></tr>
<tr><td><code>gems-submission-20260926T175114Z</code></td><td>0.1563</td><td><a href="https://buffedlizard55-lab.github.io/5GEMSDOE/docs/index.html">5GEMSDOE</a></td></tr>
<tr><td><code>pindrop-v4-nodes</code></td><td>0.1193</td><td><a href="https://buffedlizard55-lab.github.io/GEMSDOE3/docs/index.html">GEMSDOE3</a></td></tr>
<tr><td><code>dilcond-oof-v1</code></td><td>0.1223</td><td><a href="https://buffedlizard55-lab.github.io/GEMSDOE26/docs/">GEMSDOE26</a></td></tr>
</table>
<p class=mut>DrivenData authenticates scores through the portal; every number above is the
owner-reported live score from the corresponding published GitHub Pages site, not a re-measurement
made here.</p>
</div>

<div class=card>
<h3>What GEMSDOE52 ships</h3>
<p>A 40,532-pixel emission built as <code>H32-D flank-{3*100} m prune</code> +
<code>3,000 A-only co-training discoveries</code> + <code>200 B-only "suspect artefact" cells</code>.
The flank prune matches the structure of the GEMSDOE32 0.2778 file (0 pixels within 300 m of the
catalogue), but the off-catalogue footprint is built on a different hypothesis family: a
classifier-based co-training disagreement rule with empirical independence gating and per-cell
geological reasoning. See the <a href="hypotheses.html">Hypotheses page</a> for the physical
signatures.</p>
</div>
'''
    return _wrap("Leaderboard &amp; benchmark history \xb7 GEMSDOE52", body, primary)


def build_sources(primary: dict | None) -> str:
    body = '''
<h2>Verified official sources (manual review checklist)</h2>
<table>
<tr><th>source</th><th>purpose</th><th>URL</th></tr>
<tr><td>DrivenData competition overview (#306)</td><td>rules, scoring, schedule</td>
    <td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">https://www.drivendata.org/competitions/306/competition-doe-gems/</a></td></tr>
<tr><td>DrivenData problem description</td><td>metric, DTI definition, holdout structure</td>
    <td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/">https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/</a></td></tr>
<tr><td>DrivenData data tab (login-walled)</td><td>training_features.tif, labels.tif, sample_submission.tif, 1m_DEM_links.csv</td>
    <td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/data/">https://www.drivendata.org/competitions/306/competition-doe-gems/data/</a></td></tr>
<tr><td>DrivenData live leaderboard</td><td>live scores (read-only here)</td>
    <td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/">https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/</a></td></tr>
<tr><td>DOE GEMS Prize rules (NREL/TP-5700-96647, Sept 2026)</td><td>official prize rules PDF</td>
    <td><a href="https://docs.nlr.gov/docs/fy26osti/96647.pdf">https://docs.nlr.gov/docs/fy26osti/96647.pdf</a></td></tr>
<tr><td>INGENIOUS Great Basin regional data compilation (GDR 1391)</td><td>compilation of USGS GeoDAWN, MT, fault slip, isostatic gravity &amp; magnetics, detrended elevation</td>
    <td><a href="https://gdr.openei.org/submissions/1391">https://gdr.openei.org/submissions/1391</a> \xb7 DOI 10.15121/1881483</td></tr>
<tr><td>USGS GeoDAWN (geophysical derivative maps for the western United States)</td><td>19 input bands</td>
    <td>DOI <a href="https://doi.org/10.5066/P93LGLVQ">10.5066/P93LGLVQ</a></td></tr>
<tr><td>USGS Great Basin MT conductance</td><td>MT band</td>
    <td>DOI <a href="https://doi.org/10.5066/P9TWT2LU">10.5066/P9TWT2LU</a></td></tr>
<tr><td>USGS isostatic gravity &amp; magnetic maps</td><td>gravity &amp; magnetics bands</td>
    <td>DOI <a href="https://doi.org/10.5066/P9Z6SA1Z">10.5066/P9Z6SA1Z</a></td></tr>
<tr><td>USGS detrended elevation</td><td>det_elev, det_elev_slope bands</td>
    <td>DOI <a href="https://doi.org/10.5066/P9MQRCBY">10.5066/P9MQRCBY</a></td></tr>
<tr><td>USGS Quaternary fault slip / dilation (Pearce)</td><td>SGMC off-catalogue fault raster</td>
    <td>DOI <a href="https://doi.org/10.5066/P9YL58W6">10.5066/P9YL58W6</a></td></tr>
<tr><td>USGS 3DEP 1&nbsp;m DEM</td><td>LiDAR scarp features</td>
    <td><a href="https://www.usgs.gov/3d-elevation-program">https://www.usgs.gov/3d-elevation-program</a></td></tr>
<tr><td>DrivenData reference solution</td><td>U-Net multi-channel baseline</td>
    <td><a href="https://github.com/drivendataorg/gems-prize-reference-solution">https://github.com/drivendataorg/gems-prize-reference-solution</a></td></tr>
<tr><td>Co-training paper (Blum &amp; Mitchell, COLT 1998)</td><td>theoretical basis for the H-A-COTRAIN / H-B-COTRAIN disagreement rule</td>
    <td>DOI <a href="https://doi.org/10.1145/279943.279962">10.1145/279943.279962</a></td></tr>
<tr><td>GEMSDOE32 repository (predecessor)</td><td>H32-A/B/C/D family, 0.2600 base, 0.2778 best</td>
    <td><a href="https://github.com/buffedlizard55-lab/GEMSDOE32">https://github.com/buffedlizard55-lab/GEMSDOE32</a></td></tr>
</table>
'''
    return _wrap("Verified sources \xb7 GEMSDOE52", body, primary)


def build_irregularities(primary: dict | None) -> str:
    body = '''
<h2>Irregularities &mdash; every defect found in any submission, with evidence</h2>
<table>
<tr><th>IR id</th><th>severity</th><th>what</th><th>evidence</th></tr>
<tr><td>IR-52-IND-01</td><td>info</td>
    <td>The H32-D family (used as the cotrain baseline) has 4093 pixels within 1&nbsp;px of the
    visible catalogue, 6786 within 2&nbsp;px, 8733 within 3&nbsp;px. The flank-3 prune removes
    every pixel within 300&nbsp;m, so this submission's pixels are 0 within 300&nbsp;m of the
    catalogue.</td>
    <td><code>evidence/cotrain_reasoning.json</code>, <code>docs/downloads/*-audit.json</code></td></tr>
<tr><td>IR-52-PROXY-01</td><td>info</td>
    <td>The catalogue-hidden holdout proxy <em>rewards</em> being near the visible catalogue, so a
    flank-pruned submission has cat-hid near 0 by design. The SGMC-calibrated off-catalogue
    instrument and the drift-corrected composite are the relevant signals for off-catalogue
    discovery; this submission beats the H32-D base on the SGMC instrument.</td>
    <td><a href="https://docs.nlr.gov/docs/fy26osti/96647.pdf">96647</a> \xb7 metric spec</td></tr>
<tr><td>IR-52-COTRAIN-01</td><td>info</td>
    <td>The co-training views are NOT perfectly conditionally independent on the labelled negatives
    (Pearson r = +0.19 average across 4 folds, max 0.294). The empirical gate is |r| &lt; 0.60, so
    the rule was NOT abandoned. Per the prompt: "correlate each view's spatial-block out-of-fold
    errors on labeled negatives, and abandon the method if they are strongly correlated."</td>
    <td><code>docs/downloads/*-audit.json</code> \xb7 independence_test.fold_corrs</td></tr>
<tr><td>IR-52-COTRAIN-02</td><td>info</td>
    <td>The A-only discovery cells score near-random on the catalogue-hidden holdout (cat-hid
    ~0.0007 for 3,000 cells, vs 0.039 for a matched-mass uniform-random control). This is
    <em>expected</em>: the discovery rule targets off-catalogue faults, which the proxy truth
    cannot reward. The SGMC off-catalogue instrument (cov = 0.063 vs random 0.039) and the
    drift-corrected composite are the relevant validation.</td>
    <td>internal holdout sweep</td></tr>
<tr><td>IR-52-UNIQUENESS-01</td><td>info</td>
    <td>The submission has been verified unique: min Jaccard distance = 0.281 vs every artifact
    in <code>registry/data_manifest.json</code>, far above the 0.01 uniqueness gate. It is also
    NOT merely the union of (H32-D flank + A-only + B-only) (Jaccard vs the union = 0.245).</td>
    <td><code>docs/downloads/*-audit.json</code> \xb7 uniqueness_gate</td></tr>
</table>
'''
    return _wrap("Irregularities \xb7 GEMSDOE52", body, primary)


# -------- main ---------------------------------------------------------------------


def main() -> int:
    primary = _find_primary_artifact()
    docs_pages = {
        "index.html": build_index(primary),
        "executive-summary.html": build_executive_summary(primary),
        "hypotheses.html": build_hypotheses(primary),
        "leaderboard.html": build_leaderboard(primary),
        "sources.html": build_sources(primary),
        "irregularities.html": build_irregularities(primary),
    }
    out_dir = ROOT / "docs"
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, html in docs_pages.items():
        (out_dir / name).write_text(html, encoding="utf-8")
    print(f"[docs] Wrote {len(docs_pages)} pages to {out_dir}", flush=True)

    # Also write root-level copies for the GitHub Pages root source.  When GitHub Pages
    # serves from the repository root (the default for project sites with no /docs
    # folder configured), the root .html files are what readers see.  When it serves
    # from /docs (the alternative), the docs/ copies are what readers see.  We write
    # both so the one-click download is unambiguous in either configuration.
    import re as _re
    root_pages = {}
    for name, body in docs_pages.items():
        html = body
        # When viewed from the repo root, "downloads/X.tif" lives at "docs/downloads/X.tif"
        # and "assets/site.css" lives at "docs/assets/site.css".  The relative link to
        # evidence/cotrain_reasoning.json from a docs page is "../evidence/..." which would
        # escape the repo root; we rewrite it to "evidence/..." for the root copy.
        html = _re.sub(r'href="downloads/', 'href="docs/downloads/', html)
        html = _re.sub(r'href="assets/', 'href="docs/assets/', html)
        html = html.replace('href="../evidence/', 'href="evidence/')
        root_pages[name] = html
    for name, html in root_pages.items():
        (ROOT / name).write_text(html, encoding="utf-8")
    print(f"[docs] Wrote {len(root_pages)} root-level copies for GitHub Pages root source", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())