"""Generate the remaining GEMSDOE52 site pages.  Kept as a script so the HTML is reproducible."""
import pathlib

NAV = '''<a href="index.html">Overview</a><a href="executive-summary.html">Executive&nbsp;summary</a>
<a href="method.html">Method</a><a href="hypotheses.html">Hypotheses</a>
<a href="validation.html">Validation</a><a href="feed.html">Data&nbsp;feed</a>
<a href="irregularities.html">Irregularities</a><a href="sources.html">Official&nbsp;links</a>'''

HEAD = '''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} — GEMSDOE52</title><link rel="stylesheet" href="style.css"></head>
<body><a class="skip" href="#main">Skip to content</a>
<header class="top"><div class="wrap"><div class="brand">GEMS<span>DOE</span>52</div>
<nav class="top">{nav}</nav></div></header><main id="main">
'''

FOOT = ('</main><footer><div class="wrap">GEMSDOE52 · tables render from <code>docs/data/*.json</code>, '
        'regenerated by <code>scripts/refresh_feed.py</code> · <a href="sources.html">official links</a>'
        ' · <a href="irregularities.html">irregularities</a></div></footer>'
        '<script src="site.js"></script><script src="tables.js"></script></body></html>\n')


def page(title, body, cur=""):
    nav = NAV.replace(f'href="{cur}"', f'href="{cur}" aria-current="page"') if cur else NAV
    return HEAD.format(title=title, nav=nav) + body + FOOT


VALIDATION = '''
<h1>Validation: three instruments, and what each can and cannot see</h1>
<p>Every claim here is a number from <code>evidence/</code>, produced on folds built from the official
label file, with the visible catalogue masked out of both the allowed emission set and the score — the
same treatment the organiser applies (<a
href="https://community.drivendata.org/t/discussion-on-evaluation-masking-and-new-fault-truth/11516">thread
11516, posts #2 and #4, chrisk-dd</a>).</p>

<h2><span class="num">1</span> Why one instrument is not enough</h2>
<table><thead><tr><th>instrument</th><th>what is hidden</th><th class="num">held truth within 5 px of a
still-visible trace</th><th>what it can measure</th><th>what it is blind to</th></tr></thead><tbody>
<tr><td class="mono">hide</td><td>whole 8-connected catalogue components, assigned to a fold by
majority block, 4 px boundary buffer, thinned to 0.2 % prevalence</td><td class="num"><b>0.5 %</b></td>
<td>discovery of an entirely unrecognised structure</td><td>near-trace mass: a trace's own neighbours
belong to the same component, so they are hidden with it — an arm that works by extending traces looks
like noise here</td></tr>
<tr><td class="mono">block</td><td>as <code>hide</code>, plus the model is fitted only on other
quadrants and scored inside its own</td><td class="num">0.5 %</td><td>the same, with the
"the neighbouring block gives it away" leak removed</td><td>as <code>hide</code>; different region area
means a different DTI scale, so never compare across modes</td></tr>
<tr class="hi"><td class="mono">tip</td><td>the along-strike ends of traces (outer 30 % of each
component by projection on its own principal axis), bodies left visible</td><td class="num"><b>88.5 %</b></td>
<td>mapping truncation — whether a ranking puts mass where a mapped trace continues</td>
<td>wholly unrecognised structures, which is what <code>hide</code> is for</td></tr>
</tbody></table>
<p class="small">The third column is measured on the real label file, not assumed
(<code>knowledge/05_instruments_and_what_each_can_see.md</code>). It is why this repo runs two
instruments and selects the configuration that is <b>not the worst on either</b>
(<code>scripts/budget_sweep.py</code>) rather than the one that maximises the flattering number.</p>

<h2><span class="num">2</span> Arm tables</h2>
<div id="armtables"><p class="small muted">loading <code>data/holdout_tip.json</code> and
<code>data/holdout_hide.json</code>…</p></div>

<h2><span class="num">3</span> The premise test, on cells that can measure it</h2>
<div id="indep"><p class="small muted">loading <code>data/independence_*.json</code>…</p></div>

<h2><span class="num">4</span> Budget grid, both instruments</h2>
<div id="sweep"><p class="small muted">loading <code>data/budget_sweep.json</code>…</p></div>

<h2><span class="num">5</span> Gates that were run, and what they said</h2>
<ul class="tight" id="gates"><li class="muted small">loading <code>gates</code> from the holdout
tables…</li></ul>
<div class="banner red"><b>The promotion rule, applied literally.</b>
<code>registry/preregistration.json</code> requires the shipped arm to beat the naive union by 0.010 DTI
on the folds <em>and</em> beat uniform-random emission at the same budget on ≥ 3 of 4 folds. The
co-training arm failed on both instruments — <code>beats_union: not OK</code>,
<code>placement_not_mass: not OK</code>, <code>fold_support: 0/4</code> — so it is <b>not</b> what we ship,
and no weekly slot was spent on it. The tables above are that failure's record, kept published.</div>
'''

FEED = '''
<h1>Live data feed</h1>
<p class="small muted">Every page here is a renderer over <code>docs/data/*.json</code>. Nothing is typed
into the HTML, so a page cannot disagree with the repo, and a stale number appears as a stale timestamp
instead of a wrong claim.</p>
<div class="feed">feed generated <b data-feed-stamp>…</b> · leaderboard <span data-lb-status>…</span></div>
<h2><span class="num">1</span> How it stays current without a human</h2>
<ol class="steps">
<li><code>scripts/refresh_feed.py</code> copies every <code>evidence/*.json</code> verbatim, writes
<code>submission.json</code> from the newest gate report, publishes the raster and the per-candidate
reasoning CSV into <code>docs/downloads/</code>, and with <code>--fetch</code> re-scrapes the public
leaderboard, recording <code>status</code>, <code>fetched_utc</code> and the row count parsed.</li>
<li><code>.github/workflows/feed.yml</code> runs it nightly and on push, then commits the JSON.</li>
<li>The pages <code>fetch()</code> those files with <code>cache: no-store</code> and print how long ago
each source is.</li>
</ol>
<h2><span class="num">2</span> What the feed holds right now</h2>
<div id="feedlist">loading…</div>
<h2><span class="num">3</span> What is deliberately not in the feed</h2>
<p>Any file-to-score mapping, including the group's own 0.2778. The public board is participant-level and
publishes no filename, hash or upload receipt, so "this file scored that" cannot be verified from an
official source. Such statements are labelled <span class="tag warn">owner-reported</span> wherever they
appear — see <a href="irregularities.html">Irregularities</a>.</p>
'''

IRREG = '''
<h1>Irregularities, contradictions, and things that could not be verified</h1>
<p class="small muted">Flagged rather than smoothed over. Each item says what was checked and what stays
open.</p>
<table><thead><tr><th>#</th><th>finding</th><th>how it was established</th><th>what was done</th></tr></thead><tbody>
<tr class="hi"><td>IR-52-001</td><td><b>The method's premise failed.</b> The pre-registered co-training
lift test is negative on every measure used: pooled AUC 0.797→0.761 on the full grid, 1/4 folds
improved, and the arm lost to the naive union and to random emission on both instruments.</td>
<td><code>evidence/co_train_folds_*.json</code>, <code>evidence/independence_*.json</code>,
<code>evidence/holdout_*.json</code>; thresholds fixed in
<code>registry/preregistration.json</code> before any fold was scored</td>
<td>the pseudo-label round is excluded from the shipped field and the failure is on the front page; the
strata the same theory motivates are kept because they were measured separately and survived</td></tr>
<tr><td>IR-52-002</td><td><b>"0.3195 is the highest score right now" (session context) is stale</b>: live
#1 is 0.3774 and our 0.2778 sits at #13 of 16 visible rows.</td><td>leaderboard fetch, 2026-10-06</td>
<td>numbers come from the feed, so no page can repeat the stale value</td></tr>
<tr><td>IR-52-003</td><td><b>No file→score mapping is organiser-authenticated</b>, including the
<code>h33-2-b2</code> → 0.2778 mapping that the "why 0.2778" analysis rests on.</td>
<td>board inspection; sibling <code>registry/</code> status <code>NO_ELIGIBLE_SUBMISSION</code> after
GEMSDOE47 retracted its mapping</td>
<td>tagged <span class="tag warn">owner-reported</span> everywhere; the arithmetic on the file's own
pixels stands regardless, but the <em>ranking</em> claim depends on the mapping and is labelled so</td></tr>
<tr><td>IR-52-004</td><td><b>0 labels are not proven absences.</b> <code>labels.tif</code> is −1/0/1
where 0 means "not mapped"; the final test set is updated by expert review, so 0-pixels are
positive-unlabelled.</td><td>band inventory of the supplied files; staff post in thread 11527</td>
<td>stated in <code>cotrain.labelled_sets</code>; negatives keep a 3 px collar; the β=0.8 asymmetry is
modelled, not assumed away</td></tr>
<tr><td>IR-52-005</td><td><b><code>sample_submission.tif</code> ships 60,988 positive pixels sitting
exactly on label pixels</b> — copying or lightly editing it is un-original and worth ~0 under the
mask.</td><td>direct file comparison</td><td>never used as target or base; the uniqueness gate compares
the shipped file against every prior raster found on disk</td></tr>
<tr><td>IR-52-006</td><td><b>The brief's verbatim text is not recoverable from this workspace</b> — one
commit, no brief file, and a search for the theory citation returns only our own source.</td>
<td><code>git log</code>; filesystem <code>grep</code></td>
<td><code>knowledge/00_brief_as_received.md</code> itemises every directive and states it is a
reconstruction; no quotation marks are placed around invented wording</td></tr>
<tr><td>IR-52-007</td><td><b>Isolated-vs-flanking counts disagree with the sibling's published
numbers</b> (ours 24,347 / 36,547; GEMSDOE47 published 6,315 / 54,673).</td>
<td>recomputed from the label file; the cause is the dilation definition (exact 300 m disc vs box
dilation)</td><td>both definitions documented in <code>evidence/layer_screen.json</code>; we use ours and
say which</td></tr>
<tr><td>IR-52-008</td><td><b>There is no radiometric band</b> in the training cube, although the brief's
reasoning implies one; band 15 is depth to basement, band 17 is EM conductivity.</td>
<td>band-by-band inventory → <code>evidence/band_inventory.json</code></td>
<td>recorded; radiometric evidence would need an external source, hence H52-5 is blocked on provenance
rather than quietly used</td></tr>
<tr><td>IR-52-009</td><td><b>The external GDR CSVs (27,092 springs, 1,126 QFaults traces, 1 vent) are
derived files from a sibling session</b>; the GDR host is unreachable here, so they cannot be
re-downloaded and hash-checked.</td><td><code>registry/data_manifest.json</code>; failed fetch</td>
<td>not allowed to move mass in the shipped file; kept as documented corroboration, labelled derived</td></tr>
<tr><td>IR-52-010</td><td><b>The reference UNet arm cannot be reproduced here</b>: 2 cores / 3 GB cannot
hold the 27-layer float32 cube plus a torch model, and the official reference solution publishes no
scoring code.</td><td>measured resident memory of the cube (27 × 49 MB)</td>
<td>stated rather than faked; the learners here are rank-input logistic views, which are exact, cheap and
auditable — and sufficient because the metric's optimum is {0,1}, not a calibrated probability</td></tr>
<tr><td>IR-52-011</td><td><b>The rules PDF host in the brief is stale</b>: cited
<code>docs.nlr.gov</code>, live host is <code>www.nlr.gov</code>.</td><td>fetch of both</td>
<td>recorded on <a href="sources.html">sources</a>; the canonical PDF is read from the live host</td></tr>
<tr><td>IR-52-012</td><td><b>Prior-project claims about what the leaderboard "needs" were not
reproducible</b>: fitting a truth model to the eleven published scores gives best RMSE 0.1449, i.e. no
signal.</td><td>inherited analysis, re-checked by reading the sibling <code>knowledge/</code></td>
<td>not repeated here: no claim on this site is derived from inverting published scores</td></tr>
</tbody></table>
'''

SOURCES = '''
<h1>Official links for manual review</h1>
<p class="small muted">What a human needs to re-check anything on this site. Each row says whether it was
fetched this session.</p>
<h2><span class="num">1</span> Competition and rules</h2>
<table><thead><tr><th>item</th><th>link</th><th>what it settles</th><th>this session</th></tr></thead><tbody>
<tr><td>Competition page</td><td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">drivendata.org/competitions/306</a></td><td>rounds, slot limits, submission flow</td><td>fetched</td></tr>
<tr><td>Rules / evaluation</td><td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/">page 967</a></td><td>the DTI formula, α=0.2, β=0.8, R=300 m=3 px, the format list (single band, float32, [0,1], EPSG:32611, 100 m, identical bounds, null outside footprint) and the worked example</td><td>fetched; re-implemented and unit-tested against the worked example</td></tr>
<tr><td>Public leaderboard</td><td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/">leaderboard</a></td><td>#1 = 0.3774; group 0.2778 at #13 of 16 visible</td><td>fetched 2026-10-06; re-fetched on schedule by the workflow</td></tr>
<tr><td>Data tab</td><td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/data/">data</a></td><td>training cube, labels, sample submission</td><td>login-walled; the files are pinned by sha256 in <code>registry/data_manifest.json</code></td></tr>
<tr><td>Masking / new-truth clarification (staff, chrisk-dd, Sep 21)</td><td><a href="https://community.drivendata.org/t/discussion-on-evaluation-masking-and-new-fault-truth/11516">thread 11516</a></td><td>pixel-exact mask; masked pixels pay no penalty; only <i>new</i> fault truth counts; new truth <b>can</b> lie within 300 m of a known trace and such corrections are a stated goal</td><td>fetched — the most load-bearing source on this site</td></tr>
<tr><td>Test-set construction (staff, Sep 23)</td><td><a href="https://community.drivendata.org/t/what-will-the-final-test-set-look-like/11527">thread 11527</a></td><td>the Phase-2 pool uses a set updated by expert review of Phase-1 submissions → per-candidate reasoning carries option value</td><td>fetched</td></tr>
<tr><td>Programme rules (NLR)</td><td><a href="https://www.nlr.gov/docs/fy26osti/96647.pdf">nlr.gov/docs/fy26osti/96647.pdf</a></td><td>programme-level rules</td><td>fetched; the brief's <code>docs.nlr.gov</code> host is stale (IR-52-011)</td></tr>
</tbody></table>
<h2><span class="num">2</span> Method references</h2>
<table><thead><tr><th>item</th><th>link</th></tr></thead><tbody>
<tr><td>Blum &amp; Mitchell, <i>Combining labeled and unlabeled data with co-training</i>, COLT '98 — the conditional-independence premise tested here</td><td><a href="https://doi.org/10.1145/279943.279962">doi:10.1145/279943.279962</a></td></tr>
<tr><td>Official reference solution (UNet + mixture-of-costs; no scoring code published)</td><td><a href="https://github.com/drivendataorg/gems-prize-reference-solution">github.com/drivendataorg/gems-prize-reference-solution</a></td></tr>
<tr><td>Independent competitor DTI reimplementation with a held-out-segment protocol and a 3 px exclusion buffer — our parity cross-check</td><td><a href="https://github.com/Gameassassin777/gems-eval">github.com/Gameassassin777/gems-eval</a></td></tr>
</tbody></table>
<h2><span class="num">3</span> Free / official data considered</h2>
<table><thead><tr><th>source</th><th>link</th><th>licence as published</th><th>used here?</th></tr></thead><tbody>
<tr><td>USGS Geologic Data Repository — QFaults-v2, spring occurrences, volcanic vents</td><td><a href="https://www.sciencebase.gov/catalog/item/57c80074d45281cf44e8763f">sciencebase GDR faults record</a> · <a href="https://www.usgs.gov/programs/earthquake-hazards/faults">USGS Quaternary faults</a></td><td>public domain, US Government work; redistribution permitted</td><td>only as <b>derived, unverified</b> local CSVs — blocked as a mass-moving input (IR-52-009)</td></tr>
<tr><td>OpenTopography 1 m LiDAR DEMs</td><td><a href="https://opentopography.org/">opentopography.org</a></td><td>per dataset, commonly CC0/CC-BY with acknowledgement; some restricted</td><td>not fetched — host unreachable from this sandbox, and a licence claim is not something to assert from memory</td></tr>
</tbody></table>
<p class="small">Rule applied to every row: free, official, <em>confirmed obtainable from here</em>, and
licence-clear for sharing with the sponsor. Anything failing one of those is documented and is not
allowed to move mass.</p>
'''

OUT = pathlib.Path(__file__).resolve().parent.parent / "docs"
for name, body, cur in [("validation.html", VALIDATION, "validation.html"),
                        ("feed.html", FEED, "feed.html"),
                        ("irregularities.html", IRREG, "irregularities.html"),
                        ("sources.html", SOURCES, "sources.html")]:
    (OUT / name).write_text(page(name.replace(".html", "").replace("-", " ").title(), body, cur))
    print("wrote", name)
