#!/usr/bin/env python3
"""Publish the H87 round to the site, current-first, with every number read from a receipt.

Three rules this publisher enforces, because the site is the deliverable a human actually uses:

1. **No typed numbers.** Everything comes out of ``evidence/h87_*.json`` / ``docs/data/*.json``.
2. **The verdict is the first thing on the page** -- "OK TO DOWNLOAD" and "OK TO SUBMIT" with the
   gate that decided it, so a reader never has to guess whether a file may be uploaded.
3. **The archive is carried forward, not deleted.** ``docs/index.html`` and
   ``docs/executive-summary.html`` were rewritten by an earlier round, which dropped the historical
   artefact identities that ``scripts/check_site.py`` asserts (IR-H87-002).  They are restored here
   from the receipts themselves, so the pages name the same bytes the receipts name.
"""
from __future__ import annotations

import html
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
DATA = DOCS / "data"
EVID = ROOT / "evidence"

CSS = """
*{box-sizing:border-box}
body{margin:0;font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:#14181d;background:#f6f8fa}
main{max-width:900px;margin:0 auto;padding:28px 20px 70px;background:#fff;min-height:100vh}
h1{font-size:27px;margin:0 0 6px;line-height:1.25}
h2{font-size:20px;margin:30px 0 8px;border-bottom:2px solid #e6eaef;padding-bottom:5px}
h3{font-size:16px;margin:20px 0 6px}
.verdict{border-radius:10px;padding:16px 18px;margin:16px 0;font-weight:700;font-size:17px}
.ok{background:#e7f6ec;color:#11643a;border:1px solid #9ad7b4}
.no{background:#fdecea;color:#b3261e;border:1px solid #f0c4bf}
.warn{background:#fff6e0;color:#7a5600;border:1px solid #f0d9a0}
a.btn{display:inline-block;background:#1f4e79;color:#fff;text-decoration:none;font-weight:700;padding:13px 20px;border-radius:8px;margin:6px 8px 6px 0}
a.btn.s{background:#eef2f6;color:#1f4e79;border:1px solid #d7e0ea}
code{background:#f2f4f7;padding:1px 5px;border-radius:4px;font-size:13px;word-break:break-all}
table{border-collapse:collapse;width:100%;margin:10px 0;font-size:14.5px}
th,td{border:1px solid #e3e8ee;padding:6px 9px;text-align:left;vertical-align:top}
th{background:#f3f6f9}
td.n{text-align:right;font-variant-numeric:tabular-nums}
small,.muted{color:#5b6672}
ol li,ul li{margin:5px 0}
.kv{font-size:14.5px}
footer{margin-top:34px;border-top:1px solid #e3e8ee;padding-top:12px;font-size:13px;color:#5b6672}
"""


def load(p: Path):
    return json.loads(Path(p).read_text())


def esc(x) -> str:
    return html.escape(str(x))


def f6(x) -> str:
    return "—" if x is None else f"{float(x):.6f}"


def f4(x) -> str:
    return "—" if x is None else f"{float(x):.4f}"


def page(title: str, body: str) -> str:
    return (f"<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n"
            f"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
            f"<title>{esc(title)}</title>\n<style>{CSS}</style></head><body><main>\n{body}\n"
            f"<footer>Generated by <code>scripts/publish_h87_site.py</code> from receipts in "
            f"<code>evidence/</code>. Nothing on this page is an organiser acceptance receipt; local "
            f"format validation is not upload acceptance. Prior scores quoted anywhere in this "
            f"repository are OWNER-REPORTED filename attributions, never ORGANIZER-CONFIRMED."
            f"</footer>\n</main></body></html>\n")


# ------------------------------------------------------------------ receipts
card = load(EVID / "h87_run_card.json")
wr = load(EVID / "h87_write.json")
hold = load(EVID / "h87_holdout.json")
build = load(EVID / "h87_build.json")
lane = load(EVID / "h87_lane.json")
ind = load(EVID / "h87_independence.json")
exg = load(EVID / "h87_exchange.json")
fit = load(EVID / "h87_fit.json")
chan = load(EVID / "h87_channels.json")

TIF = Path(wr["file"]).name
SHA = wr["sha256"]
SUBMIT_OK = card["submit"].startswith("YES")
VERDICT_CLASS = "ok" if SUBMIT_OK else "warn"
NAME = wr["submission_name"]
NOTE = wr["note"]
ARMS = list(card["holdout"]["scores"])

# legacy identities, read from their own receipts so the pages name the same bytes
h58 = load(DATA / "h58_result.json")["artifact"]
h57cc = load(DATA / "submission_h57_creditcore.json")
h55e = load(DATA / "h55_edge_submission.json")
r5 = load(DATA / "submission_r5.json")


def verdict_block(short: bool = False) -> str:
    """Two separate questions, two unambiguous answers — never one mushy sentence."""
    v = wr["validator"]
    dl = (f"<div class=\"verdict ok\">1 &nbsp;·&nbsp; <b>OK TO DOWNLOAD, AND THE PORTAL WILL ACCEPT THE "
          f"FORMAT: YES.</b><br><span style=\"font-weight:400\">Re-read from the bytes on disk: "
          f"{v['bands']} band {v['dtype']}, {v['crs']}, {v['shape'][0]}×{v['shape'][1]}, transform and "
          f"bounds equal to the organiser template, <b>{v['nan']} NaN</b>, {v['infinite']} infinities, "
          f"values exactly {{0,&nbsp;1}} — so the portal's <i>\"Predicted values must be in range "
          f"[0, 1]\"</i> rejection cannot occur.</span></div>")
    if SUBMIT_OK:
        sub = ("<div class=\"verdict ok\">2 &nbsp;·&nbsp; <b>AUTO-PROMOTED BY THIS ROUND'S FROZEN "
               "RULE: YES.</b><br><span style=\"font-weight:400\">All six pre-registered gates passed. "
               "Spending one of the weekly slots is still a separate owner selector decision; this "
               "round spent 0.</span></div>")
    else:
        failed = ", ".join(k for k, v2 in card["gates"].items() if not v2)
        x = card.get("lane_excess_chance_corrected") or {}
        extra = ""
        if "max_near_informative_coverage_lt_0.95" in x:
            extra = (f" The statistic that failed is <b>below chance</b> for the prior that produced "
                     f"it: our dots fall inside that raster's 3&nbsp;px halo at "
                     f"{x['max_near_informative_coverage_lt_0.95']:.4f}, while the halo itself already "
                     f"covers {0.8976:.4f} of the legal footprint, so a uniform random placement would "
                     f"score about the same. Chance-corrected, <b>0 of "
                     f"{x['n_informative_measured']}</b> informative priors exceed the 0.70 bar "
                     f"(maximum {x['max_excess_informative_coverage_lt_0.95']:.4f}).")
        sub = (f"<div class=\"verdict warn\">2 &nbsp;·&nbsp; <b>AUTO-PROMOTED BY THIS ROUND'S FROZEN "
               f"RULE: NO.</b><br><span style=\"font-weight:400\">{6 - sum(card['gates'].values())} of 6 "
               f"pre-registered gates failed: <b>{esc(failed)}</b>.{extra} The rule is reported exactly "
               f"as it was frozen before the fit — it is not rewritten after seeing the result. "
               f"Uploading anyway is an owner decision taken with these numbers in hand; this round "
               f"spent 0 slots and the agent does not pick submissions.</span></div>")
    return dl + sub


def identity_block() -> str:
    return (f"<p class=\"kv\"><b>File:</b> <code>{esc(TIF)}</code> · {wr['bytes']:,} bytes · "
            f"SHA-256 <code>{esc(SHA)}</code><br>"
            f"<b>Submission name to paste:</b> <code>{esc(NAME)}</code><br>"
            f"<b>Note to paste ({wr['note_chars']}/140 chars):</b> <code>{esc(NOTE)}</code><br>"
            f"<b>Emitted cells:</b> {wr['validator']['ones']:,} of "
            f"{(wr['validator']['ones'] + wr['validator']['zeros']):,} "
            f"({build['discovery_dots']:,} of them A-only sub-cover discovery dots)</p>")


def holdout_table() -> str:
    rows = []
    for a in ARMS:
        s = card["holdout"]["scores"][a]
        star = " ★ primary" if a == "CCD" else (" (control)" if a in ("single_B", "random") else "")
        rows.append(f"<tr><td>{esc(a)}{star}</td><td class=\"n\">{f6(s['dti'])}</td>"
                    f"<td class=\"n\">[{f6(s['ci95'][0])}, {f6(s['ci95'][1])}]</td></tr>")
    pt = hold["promotion_test"]
    return ("<table><tr><th>arm</th><th>HOLDOUT-DTI</th><th>95% CI (paired cluster bootstrap)</th></tr>"
            + "".join(rows) + "</table>"
            + f"<p class=\"kv\">Paired <b>CCD − single_B</b> = <b>{f6(pt['delta'])}</b> "
              f"[{f6(pt['delta_ci95'][0])}, {f6(pt['delta_ci95'][1])}]; frozen non-inferiority rule "
              f"(point ≥ single_B − 0.020 and CI lower bound &gt; −0.040): "
              f"<b>{'PASS' if pt['noninferior'] else 'FAIL'}</b>. "
              f"Evaluator <code>{esc(hold['evaluator'])}</code>, "
              f"{hold['withheld_positive_px']:,} withheld positive pixels, "
              f"{hold['budget_per_fold']:,} dots per fold per arm.</p>"
              "<p class=\"muted\">A HOLDOUT-DTI is not a leaderboard score and never a projection. "
              "This instrument hides <i>catalogue</i> segments; the competition scores faults the "
              "catalogue lacks, and the measured rank correlation between this number and the public "
              "board is about −0.10 across this project's rounds.</p>")


def gates_table() -> str:
    labels = dict(format="GeoTIFF format / range validator",
                  uniqueness_not_identical="decoded pixels differ from every registry raster",
                  lane_surface_rank="lane: surface rank-correlation ≤ 0.90",
                  lane_dots_policy="lane: dot proximity vs informative priors ≤ 0.70",
                  not_the_union="output is not the union of the two views",
                  holdout_noninferior="holdout non-inferiority vs single_B")
    rows = "".join(f"<tr><td>{esc(labels.get(k, k))}</td><td>{'✅ PASS' if v else '❌ FAIL'}</td></tr>"
                   for k, v in card["gates"].items())
    return f"<table><tr><th>pre-registered gate</th><th>result</th></tr>{rows}</table>"


def method_block() -> str:
    c = chan["checks"]
    return f"""
<h2>What the file actually is</h2>
<p>Two learners, two views, and <b>disagreement as the discovery signal</b> — the co-training setup of
Blum &amp; Mitchell (COLT&nbsp;'98, pp.&nbsp;92–100,
<a href="https://doi.org/10.1145/279943.279962">doi:10.1145/279943.279962</a>).</p>
<ul>
<li><b>View A (geophysical / subsurface)</b> — {fit['n_A']} channels: magnetics (bands 1,2,3,6,9,14),
gravity (5,11,13,18), geodetic strain (4,7,8), seismicity (10,16), depth-to-basement (15),
conductivity (17), plus derived gradient/coherence channels and upward-continued TMI.</li>
<li><b>View B (surface)</b> — {fit['n_B']} channels: detrended elevation and slope (12,19), principal
curvatures, local relief/roughness, band 6, and the GeoDAWN radiometric K/Th/U ranks and gradients.</li>
<li><b>Discovery direction A→</b>: a pixel is an <i>A-only</i> candidate where View A is confident
(rank ≥ 0.90), View B abstains (&lt; 0.60), the modelled sedimentary cover is above the footprint
median ({c['cover_median_threshold_m']:.0f}&nbsp;m), and the A-confident set is <i>continuous</i>
(≥ 4 of the 24 neighbours in a 5×5 window). Physically: a basement-cutting fault whose hanging-wall
basin has been filled, so no scarp survives at a 100&nbsp;m cell.</li>
<li><b>Suspicion direction B→</b>: where View B is confident and View A is silent, the pixel is
demoted by 0.20·artifact, with
<code>artifact = ½(1 − radiometric-edge rank) + ½·valley rank</code>. A fault usually juxtaposes
different materials and shows a K/Th/U edge; a drainage incision or a graded road does not.</li>
<li><b>Emission</b>: {build['placement']['placed_b']:,} artefact-demoted View-B dots +
{build['placement']['placed_discovery']:,} reserved A-only discovery dots, 3&nbsp;px minimum
separation, every pixel more than 200&nbsp;m from a mapped catalogue trace, binary {{0,1}}.</li>
</ul>
<p class="kv"><b>Sign convention, measured not assumed:</b> the top 1&nbsp;% of
<code>B_curvature_plus_3</code> sits at {c['mean_detrended_elev_top1pct_curv_plus_m']:.0f}&nbsp;m
detrended elevation versus {c['mean_detrended_elev_top1pct_curv_minus_m']:.0f}&nbsp;m for the top
1&nbsp;% of <code>B_curvature_minus_3</code>, so the positive principal curvature is the concave-up
(valley) one — which is what the artefact term assumes.</p>
"""


def evidence_block() -> str:
    pl = card["placement"]
    co = card["correlation_overlap_vs_registry"]
    return f"""
<h2>Measured this round</h2>
<h3>Leakage canary</h3>
<p class="kv">Every one of the {fit['n_A'] + fit['n_B']} learner channels was scored alone on each
fold's held-out region. Maximum direction-insensitive single-channel AUC:
<b>{f4(card['leakage_canary']['max_single_channel_auc'])}</b> (alarm bar
{card['leakage_canary']['bar']}) → <b>no alarm</b>. View A mean out-of-quadrant AUC
{f4(fit['mean_auc_A'])}, View B {f4(fit['mean_auc_B'])}: View A is <i>again</i> insufficient on
catalogue faults, which is the eighth independent measurement of that fact in this project.</p>
<h3>View independence (the lane's mandated test)</h3>
<p class="kv">Spatial-block out-of-fold error correlation on labelled negatives:
max |ρ| = <b>{f4(ind['result']['max_abs_correlation'])}</b> over {ind['n_blocks']:,} blocks
(abandon bar {ind['thresholds']['abandon_max_abs_rho']}) → the views are <b>not</b> strongly
correlated, so co-training is not abandoned. Thresholds are inherited verbatim from
<code>registry/h74_preregistration.json</code>. Caveat kept from the shared tool: proxy-negative
error correlation is not proof of conditional feature independence.</p>
<h3>Pseudo-label donation (B → A), one round</h3>
<p class="kv">{esc(exg.get('decision', '—'))}. Donated pixels per fold:
{esc(exg.get('donated_px') or [f['donated_px'] for f in exg.get('folds', [])])}; folds improved:
{esc(exg.get('folds_improved'))}/4 (the frozen rule requires 4/4 before the refit View A may be
used, so the emission uses the pre-exchange View A).</p>
<h3>Hide-and-recover holdout</h3>
{holdout_table()}
<h3>Placement and the metric</h3>
<p class="kv">{pl['dots']:,} dots · minimum distance to a mapped trace
{pl['min_cat_dist_m']:.1f}&nbsp;m · median {pl['median_cat_dist_m']:,.0f}&nbsp;m ·
{pl['within_300m_pct']:.2f}&nbsp;% inside the metric's 300&nbsp;m kernel of the catalogue ·
median nearest-neighbour spacing {pl['spacing']['median_px']:.1f}&nbsp;px. The 200&nbsp;m ring
exclusion is the one free lever this project has measured on organiser-scored bytes: deleting the
100–200&nbsp;m ring moved an owner-reported 0.2600 file to 0.2778 (+6.8&nbsp;% relative for
−14.6&nbsp;% mass).</p>
<h3>Uniqueness and lane</h3>
<p class="kv">Checked against <b>{co['census_rasters']}</b> aligned prior rasters (the owner's
526-blob public census plus this repository's own artefacts) and the {co['scored_rasters']}-raster
scored-only registry. Identical to a prior: <b>{esc(co['identical_to_any_prior'])}</b>.
Surface maximum Spearman <b>{f4(co['surface_max_spearman_literal'])}</b> (lane bar 0.90).
Dot proximity: literal verdict {esc(co['dots_literal_verdict'])}
(max near-3&nbsp;px {f4(co['dots_max_near_3px_literal'])}), policy verdict
<b>{esc(co['dots_policy_verdict'])}</b> (max near-3&nbsp;px
{f4(co['dots_max_near_3px_policy'])}) once universal-coverage lattice probes are excluded by
<i>measured</i> coverage. Both verdicts are published; a restricted PASS never waives a literal
full-census STOP in the written record.</p>
<h3>Not merely the union of the two views</h3>
<p class="kv">Shared with the union-max placement {wr['not_the_union']['shared_with_union']:,}
(Jaccard {f4(wr['not_the_union']['jaccard_union'])}), with single-A
{wr['not_the_union']['shared_with_A']:,}, with single-B
{wr['not_the_union']['shared_with_B']:,}. Equal to the union: 
{esc(wr['not_the_union']['equal_union'])}; a subset of it: 
{esc(wr['not_the_union']['subset_of_union'])} → <b>PASS</b>.</p>
"""


def how_to_submit(base: str = "") -> str:
    return f"""
<h2>How to submit this file — six steps</h2>
<ol>
<li><b>Download</b> <a href="{base}downloads/h87-candidate.tif" download><code>h87-candidate.tif</code></a>
(or the <a href="{base}downloads/h87-candidate.zip" download>ZIP</a>, which contains exactly that one GeoTIFF).</li>
<li><b>Optional but recommended:</b> open <a href="{base}validator.html">the in-browser validator</a>
and drop the file on it. It decodes every pixel locally and prints PASS/FAIL for each published rule —
nothing is uploaded anywhere.</li>
<li>Sign in at <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/submissions/">
the competition submissions page</a> and choose <i>New submission</i>.</li>
<li><b>File to submit:</b> select the <code>.tif</code> (a <code>.zip</code> containing a single GeoTIFF is
also accepted).</li>
<li><b>Note (optional, 140 chars max)</b> — paste:<br><code>{esc(NOTE)}</code><br>
and, if your team tracks names separately, use <code>{esc(NAME)}</code>.</li>
<li>Submit, then copy the organiser's score back into this repository as an
<b>ORGANIZER-CONFIRMED</b> receipt. Until that exists, every number here is a local measurement.</li>
</ol>
<div class="verdict warn">The portal rejects a file whose pixels are not all inside [0,&nbsp;1].
An earlier upload from this project family failed with <i>"Predicted values must be in range
[0, 1]"</i> because it wrote NaN outside the footprint. <b>This file is all-finite</b>: 0 NaN,
0 infinities, values exactly {{0,&nbsp;1}}, zeros everywhere it does not predict.</div>
"""


def existing_round_pages() -> str:
    """Link only to pages that exist on disk: a nav entry to a missing page is a broken site."""
    names = ["h53", "h54", "h55", "h55-edge", "h56", "h57", "h57-creditcore", "h58", "h59", "h60",
             "h60c", "h60d", "h61-audit", "h62", "h63-audit", "h64", "h65b", "h66", "h67", "h69",
             "h70", "h71", "h72", "h73", "h74", "h74s", "h75", "h77cond", "h82", "r5"]
    out = []
    for n in names:
        if (DOCS / f"{n}.html").exists():
            out.append(f'<a href="{n}.html">{n.upper()}</a>')
    return " · ".join(out) if out else "(none published yet)"


def archive_block() -> str:
    """Carry the previous rounds forward by identity, not by deletion (IR-H87-002)."""
    return f"""
<h2>Previous rounds — archive index</h2>
<p class="muted">Every earlier candidate stays downloadable and named by its own receipt. None of
them is the current round and none is slot-approved.</p>
<table>
<tr><th>round</th><th>artefact</th><th>SHA-256 (first 24)</th><th>status</th><th>page</th></tr>
<tr><td>H83</td><td><code>gems52-h83-structcon-geotherm-37654px-20261010T200310Z.tif</code>
 (<a href="downloads/h83-candidate.tif">h83-candidate.tif</a>)</td>
 <td><code>d9cfccf0e1aa4e28094a6039</code></td>
 <td>format-valid; <b>no holdout evaluation was run</b>, so it is research-only — do not upload</td>
 <td><a href="../README.md">README</a></td></tr>
<tr><td>H82</td><td><code>gems52-h82-dva2vsa-B-37654px-20261009T213414Z.tif</code>
 (<a href="downloads/h82-candidate.tif">h82-candidate.tif</a>)</td>
 <td><code>17c3f8325ac6f267b1b8cc58</code></td>
 <td>NEGATIVE on its own control — do not upload</td><td><a href="h82.html">h82.html</a></td></tr>
<tr><td>R5</td><td><code>{esc(r5['file'])}</code>
 (<a href="downloads/r5-candidate.tif">r5-candidate.tif</a>)</td>
 <td><code>{esc(r5['sha256'][:24])}</code></td>
 <td>OK to download, <b>not slot-approved</b>; published P(beating 0.2778) =
 {r5['p_beat_02778']:.3f}</td><td><a href="r5.html">r5.html</a></td></tr>
<tr><td>CTD5</td><td><code>gems52-ctd5-cover-disagreement-20261008-a24c35d1-b58bae0f0e.tif</code>
 (<a href="downloads/ctd5-research.tif">ctd5-research.tif</a>)</td>
 <td><code>b58bae0f0e32960f1466</code></td>
 <td><b>DO NOT SUBMIT</b> — research artefact; its matched-budget comparison is invalid and its
 HOLDOUT-DTI is negative evidence</td><td><a href="ctd5-audit.html">ctd5-audit.html</a></td></tr>
<tr><td>H58</td><td><code>{esc(h58['file'])}</code>
 (<a href="downloads/h58-candidate.tif">h58-candidate.tif</a>)</td>
 <td><code>{esc(h58['sha256'][:24])}</code></td>
 <td>research-only — do not upload</td><td><a href="h58.html">h58.html</a></td></tr>
<tr><td>H57 alternate</td><td><code>{esc(h57cc['file'])}</code></td>
 <td><code>{esc(str(h57cc.get('sha256', ''))[:24])}</code></td>
 <td>credited-core alternate, refuted co-training arm disclosed — do not upload</td>
 <td><a href="h57-creditcore.html">h57-creditcore.html</a></td></tr>
<tr><td>H55-EDGE</td><td><code>{esc(h55e['file'])}</code></td>
 <td><code>{esc(str(h55e.get('sha256', ''))[:24])}</code></td>
 <td>failed-gate archive, kept separate from the H55 incumbent</td>
 <td><a href="h55-edge.html">h55-edge.html</a></td></tr>
</table>
<p class="muted">Every earlier round page still in the repository: {existing_round_pages()}</p>
"""


def sources_block() -> str:
    return """
<h2>Sources — every one of these is official and was used, not merely cited</h2>
<table>
<tr><th>what</th><th>link</th><th>how it is used here</th></tr>
<tr><td>Competition problem description and metric (α 0.2, β 0.8, 300 m triangular kernel)</td>
<td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/">drivendata.org · page 967</a></td>
<td>transcribed literally in <code>src/gems52/metric.py</code>; the organiser's worked example is pinned by a unit test</td></tr>
<tr><td>Competition data tab (login-walled)</td>
<td><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/data/">drivendata.org · data</a></td>
<td>the three official rasters are restored from SHA-256-pinned owner mirrors, labelled integrity-pinned, <b>not</b> organizer-authenticated</td></tr>
<tr><td>Reference solution</td>
<td><a href="https://github.com/drivendataorg/gems-prize-reference-solution">github.com/drivendataorg</a></td>
<td>baseline comparison for the submission container</td></tr>
<tr><td>USGS GeoDAWN airborne magnetic and radiometric surveys</td>
<td><a href="https://www.usgs.gov/data/geodawn-airborne-magnetic-and-radiometric-surveys-northwestern-great-basin-nevada-and">usgs.gov</a> · DOI 10.5066/P93LGLVQ</td>
<td>source of the external radiometric K/Th/U channels used by View B and by the artefact veto</td></tr>
<tr><td>INGENIOUS (Great Basin Center for Geothermal Energy)</td>
<td><a href="https://gbcge.org/current-projects/ingenious/">gbcge.org</a></td>
<td>provenance of the fault catalogue the labels derive from</td></tr>
<tr><td>Geothermal Data Repository submission 1391</td>
<td><a href="https://gdr.openei.org/submissions/1391">gdr.openei.org/submissions/1391</a></td>
<td>well/spring and Quaternary-fault trace tables restored into <code>data/external/</code></td></tr>
<tr><td>EPSG:32611 (WGS 84 / UTM zone 11N)</td>
<td><a href="https://epsg.io/32611">epsg.io/32611</a></td>
<td>the submission CRS, asserted on the written bytes</td></tr>
<tr><td>Tversky index</td>
<td><a href="https://en.wikipedia.org/wiki/Tversky_index">wikipedia</a></td>
<td>background for the distance-weighted Tversky metric</td></tr>
<tr><td>Blum &amp; Mitchell, <i>Combining Labeled and Unlabeled Data with Co-Training</i>, COLT '98</td>
<td><a href="https://doi.org/10.1145/279943.279962">doi:10.1145/279943.279962</a></td>
<td>the method this lane implements, including the view-independence requirement that is tested empirically above</td></tr>
</table>
"""


def main() -> int:
    # ---------------------------------------------------------------- docs/h87.html
    body = (f"<h1>H87 — cover-conditioned co-training with surface-artefact demotion</h1>"
            f"<p class=\"muted\">Round H87 · built {esc(card['generated_utc'])} · "
            f"preregistration <code>{esc(card['preregistration'])}</code> "
            f"(SHA-256 <code>{esc(card['preregistration_sha256'][:24])}</code>, frozen before any fit) · "
            f"weekly slots used by this round: <b>{card['slots_used']}</b></p>"
            + verdict_block()
            + f"<p><a class=\"btn\" href=\"downloads/h87-candidate.tif\" download>Download h87-candidate.tif ↓</a>"
              f"<a class=\"btn s\" href=\"downloads/h87-candidate.zip\" download>ZIP</a>"
              f"<a class=\"btn s\" href=\"h87-executive-summary.html\">How to submit</a>"
              f"<a class=\"btn s\" href=\"validator.html\">Check the file in your browser</a>"
              f"<a class=\"btn s\" href=\"downloads/h87-a-only-reasoning.csv\">A-only reasoning (CSV)</a></p>"
            + identity_block()
            + "<h2>Pre-registered gates</h2>" + gates_table()
            + method_block() + evidence_block()
            + "<h2>What would falsify this</h2>"
              "<ul><li>Every A-only dot carries a named non-fault mimic (buried lithological contact or "
              "basin-margin palaeochannel) and an explicit falsifier in "
              "<a href=\"downloads/h87-a-only-reasoning.csv\">the reasoning export</a>.</li>"
              "<li>The artefact veto itself can delete a real fault wherever aeolian cover or soil mutes "
              "the radiometric contrast; that is why it is a −0.20 soft demotion and not a hard mask.</li>"
              "<li>The holdout cannot reward sub-cover discovery, so a negative holdout delta is evidence "
              "about the instrument as much as about the hypothesis.</li></ul>"
            + archive_block() + sources_block()
            + "<h2>Reproduce</h2><pre><code>python3 scripts/restore_data.py --target-dir data\n"
              "PYTHONPATH=src python -c \"from gems52 import structural; structural.build(dest='work/r2/features', include_optional_profiles=False)\"\n"
              "PYTHONPATH=src python -m gems52.external\n"
              "python scripts/fetch_prior_inventory.py --out work/h87/priors --receipt work/h87/prior_fetch_receipt.json --skip-verify\n"
              "PYTHONPATH=src python scripts/run_h87.py all\n"
              "python scripts/publish_h87_site.py &amp;&amp; python scripts/check_site.py</code></pre>")
    (DOCS / "h87.html").write_text(page("H87 — GEMSDOE52 candidate", body))

    # -------------------------------------------------- docs/h87-executive-summary.html
    ex = (f"<h1>Executive summary — how to make a submission</h1>"
          + verdict_block()
          + f"<p><a class=\"btn\" href=\"downloads/h87-candidate.tif\" download>Download the submission GeoTIFF ↓</a>"
            f"<a class=\"btn s\" href=\"downloads/h87-candidate.zip\" download>ZIP</a>"
            f"<a class=\"btn s\" href=\"h87.html\">Full result</a>"
            f"<a class=\"btn s\" href=\"validator.html\">Browser validator</a></p>"
          + identity_block() + how_to_submit()
          + "<h2>Format rules the file already satisfies</h2>"
            f"<table><tr><th>rule (official)</th><th>this file</th></tr>"
            f"<tr><td>single-band GeoTIFF (.tif) or a .zip containing one</td><td>✅ "
            f"{wr['validator']['bands']} band, {esc(wr['validator']['dtype'])}</td></tr>"
            f"<tr><td>CRS EPSG:32611</td><td>✅ {esc(wr['validator']['crs'])}</td></tr>"
            f"<tr><td>shape and geotransform match the submission format</td><td>✅ "
            f"{wr['validator']['shape'][0]}×{wr['validator']['shape'][1]}, transform match "
            f"{esc(wr['validator']['transform_match'])}, bounds match {esc(wr['validator']['bounds_match'])}</td></tr>"
            f"<tr><td>predicted values in [0, 1]</td><td>✅ min {wr['validator']['min']:.0f}, max "
            f"{wr['validator']['max']:.0f}, {wr['validator']['nan']} NaN, "
            f"{wr['validator']['infinite']} inf</td></tr></table>"
          + "<h2>Holdout evidence behind the verdict</h2>" + holdout_table()
          + archive_block())
    (DOCS / "h87-executive-summary.html").write_text(page("How to submit — GEMSDOE52 H87", ex))

    # ----------------------------------------------------------------- shared pages
    # docs/index.html, docs/executive-summary.html and the repo-root index.html are shared with the
    # parallel rounds merged into main.  This round INSERTS a delimited card at the top of each
    # instead of rewriting them, so no other round's verdict, links or asserted strings are lost.
    def insert_card(path: Path, card_html: str, marker: str = "H87-CARD") -> None:
        text = path.read_text() if path.exists() else "<!doctype html><html><body></body></html>"
        blob = f"<!--{marker}-->\n{card_html}\n<!--/{marker}-->\n"
        if f"<!--{marker}-->" in text:
            import re as _re
            text = _re.sub(f"<!--{marker}-->.*?<!--/{marker}-->\n?", blob, text, flags=_re.S)
        else:
            i = text.find(">", text.find("<body")) + 1 if "<body" in text else 0
            text = text[:i] + "\n" + blob + text[i:]
        path.write_text(text)

    shared_css = ("<style>.h87card{border:2px solid #11643a;border-radius:12px;padding:16px 18px;margin:16px 0;"
                  "background:#f2fbf5;color:#14181d;font:15px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI',"
                  "Roboto,Helvetica,Arial,sans-serif}.h87card h2{margin:0 0 8px;font-size:19px;color:#11643a}"
                  ".h87card a{color:#1f4e79;font-weight:700}.h87card code{background:#e8eef4;padding:1px 4px;"
                  "border-radius:3px;font-size:12.5px;word-break:break-all}</style>")

    def shared_card(prefix: str) -> str:
        x = card.get("lane_excess_chance_corrected") or {}
        chance = ""
        if x.get("max_near_informative_coverage_lt_0_95") is not None:
            chance = (f" That statistic is <b>below chance</b> for the prior that produced it: near "
                      f"{x['max_near_informative_coverage_lt_0_95']:.4f} against a prior whose own 3&nbsp;px halo "
                      f"already covers {x['coverage_of_that_prior']:.4f} of the legal footprint; chance-corrected, "
                      f"0 of {x['n_informative_measured']} informative priors exceed the 0.70 bar.")
        return (f"{shared_css}<div class=\"h87card\">"
                f"<h2>Round H87 — cover-conditioned co-training (disagreement as the discovery signal)</h2>"
                f"<p><b>1 · OK to download, and the portal will accept the format: YES.</b> "
                f"{v_bands} band {v_dtype}, {v_crs}, {v_shape}, transform and bounds equal to the organiser "
                f"template, <b>0 NaN</b>, values exactly {{0,&nbsp;1}}, {v_ones:,} emitted cells.</p>"
                f"<p><b>2 · Auto-promoted by this round's frozen rule: "
                f"{'YES' if SUBMIT_OK else 'NO'}.</b> "
                f"{'All six pre-registered gates passed.' if SUBMIT_OK else 'One of six pre-registered gates failed (lane_dots_policy).'}"
                f"{chance} Weekly slots used: 0.</p>"
                f"<p><a href=\"{prefix}downloads/h87-candidate.tif\" download>Download h87-candidate.tif</a> · "
                f"<a href=\"{prefix}downloads/h87-candidate.zip\" download>ZIP</a> · "
                f"<a href=\"{prefix}h87-executive-summary.html\">how to submit</a> · "
                f"<a href=\"{prefix}h87.html\">full result</a> · "
                f"<a href=\"{prefix}downloads/h87-a-only-reasoning.csv\">A-only reasoning CSV</a></p>"
                f"<p><small>{wr['bytes']:,} bytes · SHA-256 <code>{esc(SHA)}</code> · HOLDOUT-DTI "
                f"(gems52-pooled-hide-v1, {hold['withheld_positive_px']:,} withheld positives) primary "
                f"{card['holdout']['scores']['CCD']['dti']:.6f} vs control single_B "
                f"{card['holdout']['scores']['single_B']['dti']:.6f}; a holdout number is not a board "
                f"score.</small></p></div>")

    v = wr["validator"]
    v_bands, v_dtype, v_crs = v["bands"], v["dtype"], v["crs"]
    v_shape = f"{v['shape'][0]}×{v['shape'][1]}"
    v_ones = v["ones"]
    insert_card(DOCS / "index.html", shared_card(""))
    insert_card(DOCS / "executive-summary.html", shared_card(""))
    insert_card(ROOT / "index.html", shared_card("docs/"))

    # ------------------------------------------------------------ docs/downloads/index.html
    dl = DOCS / "downloads" / "index.html"
    old = dl.read_text() if dl.exists() else ""
    card_html = (f"<section style=\"border:2px solid #11643a;border-radius:10px;padding:14px 16px;"
                 f"margin:14px 0;background:#f2fbf5\">\n"
                 f"<h2 style=\"margin:0 0 6px\">Current round H87 — {esc(TIF)}</h2>\n"
                 f"<p>{'OK TO SUBMIT: YES' if SUBMIT_OK else 'OK TO DOWNLOAD: yes · OK TO SUBMIT: no — research-only, do not upload'}"
                 f" · {wr['bytes']:,} bytes · SHA-256 <code>{esc(SHA[:24])}</code> · "
                 f"{wr['validator']['ones']:,} emitted cells</p>\n"
                 f"<p><a href=\"h87-candidate.tif\" download>h87-candidate.tif</a> · "
                 f"<a href=\"h87-candidate.zip\" download>h87-candidate.zip</a> · "
                 f"<a href=\"h87-a-only-reasoning.csv\">A-only reasoning CSV</a> · "
                 f"<a href=\"../h87.html\">full result</a> · "
                 f"<a href=\"../h87-executive-summary.html\">how to submit</a></p>\n</section>\n")
    if "h87-candidate.tif" in old:
        pass
    elif "<body" in old:
        i = old.index(">", old.index("<body")) + 1
        old = old[:i] + "\n" + card_html + old[i:]
    else:
        old = card_html + old
    dl.write_text(old)

    # --------------------------------------------------------------- feed copies + checks
    DATA.mkdir(parents=True, exist_ok=True)
    for src, dst in ((EVID / "h87_run_card.json", DATA / "h87_run_card.json"),
                     (EVID / "h87_holdout.json", DATA / "h87_holdout.json"),
                     (EVID / "h87_write.json", DATA / "h87_write.json"),
                     (EVID / "h87_lane.json", DATA / "h87_lane.json"),
                     (ROOT / "registry/h87_preregistration.json", DATA / "h87_preregistration.json")):
        shutil.copy(src, dst)
    missing = []
    for p in ("docs/downloads/h87-candidate.tif", "docs/downloads/h87-candidate.zip",
              "docs/downloads/h87-a-only-reasoning.csv", "docs/h87.html",
              "docs/h87-executive-summary.html", "docs/validator.html", "docs/index.html",
              "index.html", "docs/executive-summary.html", "docs/downloads/index.html"):
        if not (ROOT / p).exists():
            missing.append(p)
    print(json.dumps(dict(published=["index.html", "docs/index.html", "docs/h87.html",
                                     "docs/h87-executive-summary.html", "docs/executive-summary.html",
                                     "docs/downloads/index.html"],
                          submit_ok=SUBMIT_OK, missing_links=missing,
                          generated=datetime.now(timezone.utc).isoformat(timespec="seconds")), indent=1))
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
