#!/usr/bin/env python3
"""Publish the H88 round to the GitHub Pages site (current-first, archive preserved).

Reads receipts only (evidence/h88_*.json, evidence/h61_independence.json); no hand-copied
numbers. Writes docs/h88.html (round detail) and rewrites docs/index.html as current-first:
the H88 block on top, the previous (H87) index preserved verbatim inside one collapsed
<details> archive, plus links to the older archive pages. Idempotent.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVID = ROOT / "evidence"
DOCS = ROOT / "docs"


def load(name):
    return json.loads((EVID / name).read_text())


def fmt(x, nd=6):
    return f"{x:.{nd}f}" if isinstance(x, (int, float)) else str(x)


def pill(ok, yes="PASS", no="FAIL"):
    cls = "pill-ok" if ok else "pill-err"
    txt = yes if ok else no
    return f'<span class="pill {cls}">{txt}</span>'


CSS = """
:root{--bg:#0f1117;--fg:#e8eaed;--accent:#4fc3f7;--ok:#66bb6a;--warn:#ffa726;--err:#ef5350;--card:#1a1d27;--border:#2d3040}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:var(--bg);color:var(--fg);line-height:1.6;padding:0}
.container{max-width:940px;margin:0 auto;padding:24px 20px}
h1{font-size:1.8rem;margin-bottom:8px;color:var(--accent)}
h2{font-size:1.3rem;margin:28px 0 12px;color:var(--accent);border-bottom:1px solid var(--border);padding-bottom:6px}
h3{font-size:1.1rem;margin:20px 0 8px}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline}
code{background:#1e2130;padding:2px 6px;border-radius:3px;font-size:0.9em}
.download-box{background:linear-gradient(135deg,#1a237e,#0d47a1);border:2px solid var(--accent);border-radius:12px;padding:28px;margin:20px 0;text-align:center}
.download-box h2{color:#fff;border:none;margin:0 0 12px;font-size:1.5rem}
.download-box p{color:#b3e5fc;margin:8px 0}
.btn{display:inline-block;background:var(--accent);color:#000;font-weight:700;padding:14px 32px;border-radius:8px;font-size:1.1rem;margin:8px;transition:all .2s}
.btn:hover{background:#81d4fa;text-decoration:none;transform:translateY(-1px)}
.btn-zip{background:#78909c;color:#fff}
.btn-zip:hover{background:#90a4ae}
.banner{border-radius:10px;padding:16px 20px;margin:16px 0;font-size:1.05rem;font-weight:600}
.banner-ok{background:#10331a;border:2px solid var(--ok);color:#a5d6a7}
.banner-no{background:#3a1214;border:2px solid var(--err);color:#ef9a9a}
.card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:18px;margin:12px 0}
table{width:100%;border-collapse:collapse;margin:12px 0;font-size:0.9rem}
th,td{padding:8px 12px;text-align:left;border-bottom:1px solid var(--border)}
th{color:var(--accent);font-weight:600}
.pass{color:var(--ok);font-weight:700}
.fail{color:var(--err);font-weight:700}
.warn{color:var(--warn);font-weight:700}
.pill{display:inline-block;padding:2px 10px;border-radius:12px;font-size:0.8rem;font-weight:600}
.pill-ok{background:#1b5e20;color:#a5d6a7}
.pill-err{background:#4a1012;color:#ef9a9a}
.pill-warn{background:#4a2800;color:#ffcc80}
.copy-box{background:#1e2130;border:1px solid var(--border);border-radius:6px;padding:12px 16px;font-family:monospace;font-size:0.9rem;margin:8px 0;word-break:break-all}
.footer{margin-top:40px;padding-top:20px;border-top:1px solid var(--border);font-size:0.85rem;color:#777}
details{margin:18px 0}
summary{cursor:pointer;color:var(--accent);font-weight:600}
"""


def head(title):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>{CSS}</style>
</head>
<body>
<div class="container">
"""


FOOT = """<div class="footer">GEMSDOE52 · DOE GEMS Prize (DrivenData #306) · generated by
<code>scripts/publish_h88_site.py</code> from evidence receipts · every score labelled
HOLDOUT-DTI is local, not organizer-confirmed.</div>
</div></body></html>
"""


def main():
    card = load("h88_run_card.json")
    ho = load("h88_holdout.json")
    fit = load("h88_fit.json")
    build = load("h88_build.json")
    chan = load("h88_channels.json")
    rea = load("h88_reasoning.json")
    indep = load("h61_independence.json")

    sc = ho["pooled"]["scores"]
    pd = ho["pooled"]["paired_differences"]
    withheld = sc["B_ABS"]["withheld_positive_pixels"]
    submit_ok = bool(card["ok_to_download_and_submit"]["submit"])
    verdict = card["verdict"]
    tif = Path(card["raster"]["path"])
    fname = tif.name
    rel = f"downloads/{fname}"
    zip_rel = rel.replace(".tif", ".zip")
    kb = card["raster"]["bytes"] // 1024
    zkb = int((tif.with_suffix(".zip").stat().st_size) // 1024)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    banner = (f'<div class="banner banner-ok">✅ DOWNLOAD OK — SUBMIT OK: this file passed the '
              f'preregistered promote rule (holdout, canaries, independence, union, lane, format, '
              f'uniqueness). Promotion to a real weekly slot remains the selector step.</div>'
              if submit_ok else
              f'<div class="banner banner-no">⬇ DOWNLOAD OK (research) — ⛔ DO NOT SUBMIT: '
              f'{card["ok_to_download_and_submit"]["reason"]}. A negative result is a deliverable; '
              f'spending a weekly slot on it is forbidden by the project\'s own rules.</div>')

    arm_rows = []
    for a in ("B_ABS", "single_B", "ABS_only", "disagree_Aonly", "random"):
        s = sc[a]
        arm_rows.append(
            f"<tr><td><code>{a}</code>{' <b>(candidate)</b>' if a=='B_ABS' else ''}</td>"
            f"<td>{fmt(s['dti'])}</td><td>[{fmt(s['ci95'][0])}, {fmt(s['ci95'][1])}]</td></tr>")
    diff = pd["single_B"]
    fold_rows = []
    for fr in fit["folds"]:
        fold_rows.append(
            f"<tr><td>{fr['fold']}</td><td>{fmt(fr['auc']['single_B'],4)}</td>"
            f"<td>{fmt(fr['auc']['B_ABS'],4)}</td><td>{fmt(fr['auc']['ABS_only'],4)}</td>"
            f"<td>{fmt(fr['canary_max'],4)}</td></tr>")

    lane_d = card["correlation_vs_registry"]["dots"]
    lane_s = card["correlation_vs_registry"]["surface"]

    page = head("GEMSDOE52 — H88 Antithetic Basement-Step Co-Training")
    page += f"""
<h1>GEMSDOE52 — H88 Antithetic Basement-Step Co-Training</h1>
<p style="color:#999;margin-bottom:4px">DOE GEMS Prize (DrivenData #306) · fault discovery ·
lane: two-view co-training with disagreement as the discovery signal</p>
<p style="color:#999;font-size:0.9rem">Published {now} · verdict:
{pill(verdict == 'promote', verdict.upper(), verdict.upper())} · slots used: 0</p>

{banner}

<div class="download-box">
<h2>⬇ SUBMISSION FILE (one click)</h2>
<p>Single-band GeoTIFF, float32, EPSG:32611, all pixels finite in [0,1] (zeros-outside container).</p>
<a class="btn" href="{rel}" download>📥 Download .tif ({kb} KB)</a>
<a class="btn btn-zip" href="{zip_rel}" download>📦 Download .zip ({zkb} KB)</a>
<p style="font-size:0.85rem;margin-top:12px">
<strong>Filename:</strong> <code>{fname}</code><br>
<strong>SHA-256:</strong> <code>{card['raster']['sha256']}</code><br>
<strong>Emitted mass:</strong> {card['raster']['ones']:,} pixels, values {{0,1}}, ≥ 200 m from every
mapped fault, 3 px minimum spacing</p>
</div>

<div class="card">
<h3>Portal fields (copy-paste)</h3>
<p><strong>Submission name:</strong></p>
<div class="copy-box">{card['submission_name']}</div>
<p><strong>Note (≤ 140 chars):</strong></p>
<div class="copy-box">{card['submission_note']}</div>
<p>Submit at the <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/submissions/">
DrivenData submission page</a> (login required). Upload the <code>.tif</code> (or the <code>.zip</code>),
paste the name and note, click Submit. Format matches <code>sample_submission.tif</code> CRS / shape /
geotransform — verified from disk.</p>
</div>

<h2>1 · The hypothesis (preregistered, SHA-pinned)</h2>
<div class="card">
<p>{card['hypothesis']}</p>
<p><strong>Mechanism.</strong> {card['mechanism']}</p>
<p><strong>Named non-fault mimic.</strong> {card['non_fault_process']}</p>
<p>Preregistration: <code>knowledge/81_hypotheses_H88_preregistered.md</code>, pinned by
<code>registry/h88_preregistration.json</code>; the runner refuses to start if the document moves.</p>
</div>

<h2>2 · Holdout validation (evidence class: HOLDOUT-DTI)</h2>
<div class="card">
<p>Evaluator <code>{ho['pooled']['evaluator_version']}</code> (α {ho['pooled']['alpha']},
β {ho['pooled']['beta']}, 300 m triangular kernel) · whole-segment hide-and-recover quadrant folds,
80 px buffer, visible catalogue masked pixel-exactly · {withheld:,} withheld positive pixels ·
9,400 dots per arm per fold, 3 px spacing · paired physical 20 km spatial-cluster bootstrap,
1,000 draws.</p>
<table><tr><th>arm</th><th>HOLDOUT-DTI</th><th>95% CI</th></tr>{''.join(arm_rows)}</table>
<p><strong>Paired B_ABS − single_B:</strong> Δ {fmt(diff['delta'])}, 95% CI
[{fmt(diff['ci95'][0])}, {fmt(diff['ci95'][1])}] → promote rule (CI lower bound &gt; 0):
{pill(card['promote_rule_met']['ci_lower_bound_gt_0'])}</p>
<p><strong>Control reproduction:</strong> single_B {fmt(sc['single_B']['dti'])} vs committed 0.174571;
random {fmt(sc['random']['dti'])} vs committed 0.080426 (tolerance 1e−3; the runner aborts on drift).</p>
<p style="color:#999;font-size:0.85rem">HOLDOUT-DTI is the local shared evaluator, NOT an organizer
score. Holdout hides catalogue faults; the board scores off-catalogue faults — a holdout win is
necessary, not sufficient (knowledge/76).</p>
</div>

<h2>3 · The brief's mandated checks</h2>
<table>
<tr><th>check</th><th>result</th></tr>
<tr><td>Independence: block-level OOF error correlation of the views on labelled negatives
(bar |ρ| ≤ 0.60)</td><td>max |ρ| {fmt(indep['pre']['max_abs_correlation'],4)} → {pill(indep['allow_exchange'])}</td></tr>
<tr><td>Pseudo-labels: exactly one confident→abstain whole-segment exchange, buffer-respecting</td>
<td>{indep['allow_exchange'] and 'measured (never shipped, N-1 settled)' or 'skipped (independence gate)'}</td></tr>
<tr><td>Leakage canary: each ABS channel alone, per-fold AUC (alarm ≥ 0.90)</td>
<td>max {fmt(max(fr['canary_max'] for fr in fit['folds']),4)} → {pill(not fit['canary_alarm'])}</td></tr>
<tr><td>Single-view baseline comparison (brief: co-training can amplify bias)</td>
<td>single_A / single_B / union / disagreement arms in <code>evidence/h61_holdout.json</code></td></tr>
<tr><td>A-only geological reasoning (Phase-2 reviewers)</td>
<td>{rea['segments']} segments with shipped dots in <code>downloads/h88-a-only-reasoning.csv</code></td></tr>
<tr><td>Not merely the union of the two views (bar Jaccard &lt; 0.50)</td>
<td>{' · '.join(f"{k.split('jaccard_vs_')[1]} {fmt(v,4)}" for k, v in card['union_not'].items())} → {pill(card['promote_rule_met']['union_check_pass'])}</td></tr>
<tr><td>Normalized to [0,1], GeoTIFF written, metric-aware placement (3 px spacing), uniqueness gate</td>
<td>{card['raster']['ones']:,} px · {pill(True)}</td></tr>
<tr><td>Validator: no NaN inside footprint, values in [0,1], CRS/shape/transform match</td>
<td>{pill(card['validator']['all_finite'])} (zeros-outside container, IR-H85-004)</td></tr>
<tr><td>Uniqueness vs {card['uniqueness']['n_priors_checked']} registry rasters (decoded pixels)</td>
<td>{pill(card['uniqueness']['distinct_from_every_comparable_prior'])} · identical to a prior:
{pill(not card['uniqueness']['identical_to_a_prior'], 'NO', 'YES')}</td></tr>
<tr><td>Lane, surface phase: rank ≤ 0.90 and near-3px ≤ 0.70 vs one registry raster</td>
<td>Spearman max {fmt(lane_s['literal_max_spearman'],4)} (literal), policy near3
{fmt(lane_s['policy_max_near3'],4)} → {pill(lane_s['policy_verdict'] == 'PASS', lane_s['policy_verdict'], lane_s['policy_verdict'])}</td></tr>
<tr><td>Lane, dots phase</td>
<td>Spearman max {fmt(lane_d['literal_max_spearman'],4)} · near-3px literal
{fmt(lane_d['literal_max_near3'],4)} ({lane_d['n_probes']} universal-coverage probes inflate the
literal number for ANY raster, incl. random) · policy near3 {fmt(lane_d['policy_max_near3'],4)} →
{pill(lane_d['policy_verdict'] == 'PASS', lane_d['policy_verdict'], lane_d['policy_verdict'])}</td></tr>
</table>

<h2>4 · Per-fold fit & canaries</h2>
<table><tr><th>fold</th><th>AUC single_B</th><th>AUC B_ABS</th><th>AUC ABS_only</th>
<th>canary max</th></tr>{''.join(fold_rows)}</table>

<h2>5 · Why 0.2778 scored highest, and what beating it requires</h2>
<div class="card">
<p>Measured from the champion bytes (<code>data/reference/h33-2-b2-zeros.tif</code>) in
<code>knowledge/76</code>: the champion is a 37,654-pixel binary file at 3 px spacing, ≥ 223.6 m
from every mapped fault — the 0.2600 surface field with the ≤ 200 m catalogue ring deleted. Under
the metric's own arithmetic (DTI ≈ T / (0.2·S + 0.8·|G|), |G| ≈ 14,089 solved from the two
owner-reported scores), beating 0.3195 needs either <strong>+15% credit density</strong> at equal
mass or <strong>−33% mass</strong> at equal credit. Across twelve owner-scored family rasters
Spearman(mass, score) = −0.93: the cheapest unspent lever is shipping less (queued as H88-MASS).
None of this is a board forecast; it is arithmetic on published numbers.</p>
</div>

<h2>6 · Sources (for manual review)</h2>
<ul>
<li><a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">DOE GEMS Prize — DrivenData #306</a> (problem, metric, rules; login-walled data tab)</li>
<li><a href="https://doi.org/10.1145/279943.279962">Blum &amp; Mitchell, COLT '98, pp. 92–100</a> — co-training</li>
<li><a href="https://www.usgs.gov/data/geodawn-airborne-magnetic-and-radiometric-surveys-northwestern-great-basin-nevada-and">USGS GeoDAWN airborne magnetic &amp; radiometric surveys</a></li>
<li><a href="https://doi.org/10.5066/P93LGLVQ">USGS GeoDAWN data release, DOI 10.5066/P93LGLVQ</a></li>
<li><a href="https://gdr.openei.org/submissions/1391">INGENIOUS GDR submission 1391</a> (CC BY 4.0)</li>
<li><a href="https://en.wikipedia.org/wiki/Tversky_index">Tversky index</a> (DTI generalises it)</li>
<li><a href="https://epsg.io/32611">EPSG:32611</a> — competition CRS</li>
</ul>
<p>Full receipts: <code>evidence/h88_run_card.json</code>, <code>evidence/h88_holdout.json</code>,
<code>evidence/h88_fit.json</code>, <code>evidence/h88_channels.json</code>,
<code>evidence/h88_build.json</code>, <code>evidence/h88_reasoning.json</code>,
<code>evidence/h61_*.json</code>. Round detail page: <a href="h88.html">h88.html</a>.</p>
"""
    # archive: previous index verbatim (idempotent: recover the already-archived page on re-run)
    prev = (DOCS / "index.html").read_text()
    start = prev.find("<!--ARCHIVE-START-->")
    end = prev.find("<!--ARCHIVE-END-->")
    if start != -1 and end != -1:
        prev = prev[start + len("<!--ARCHIVE-START-->"):end]
    page += f"""
<h2>Verdict summary (this round)</h2>
<table>
<tr><th>OK to download?</th><td class="pass">YES — format-valid research artefact, SHA-pinned below.</td></tr>
<tr><th>OK to submit?</th><td>{'<span class="pass">YES — promote rule passed; promotion to a weekly slot is the selector step.</span>' if submit_ok else '<span class="fail">NO — DO NOT SUBMIT. ' + card['ok_to_download_and_submit']['reason'] + '</span>'}</td></tr>
</table>

<h2>Archive — previous rounds</h2>
<div class="card">
<p><strong>Standing guardrails (carried forward, not re-litigated):</strong> NO CERTIFIED LEADERBOARD GAIN is ever advertised by this site — every number is HOLDOUT-DTI (local evaluator) or
OWNER-REPORTED, never organizer-confirmed. CTD5 (<code>downloads/ctd5-research.tif</code>) is
research-only: DO NOT SUBMIT (verdict negative, strict holdout not valid for promotion).
H83 (<a href="downloads/h83-candidate.tif">downloads/h83-candidate.tif</a>,
<a href="downloads/h83-candidate.zip">zip</a>) is DOWNLOAD YES / DO NOT SUBMIT (its geo-concordance
field scored below the random control, knowledge/78). H84/H85/H86 candidates
(<a href="downloads/h84-candidate.tif">h84</a>, <a href="downloads/h85-candidate.tif">h85</a>,
<a href="downloads/h86-candidate.tif">h86</a>) are likewise research-only, DO NOT SUBMIT.
No H55-1 paired-shoulders candidate was ever built or promoted: no h55-1 TIFF was built.</p>
</div>
<details><summary>H87 — co-training wavelength contrast (previous index page, verbatim; build
receipt only — it was never holdout-validated, so treat its PROMOTE label as research-only,
DO NOT SUBMIT without validation)</summary>
<!--ARCHIVE-START-->
{prev}
<!--ARCHIVE-END-->
</details>
<p>Older archived round pages:
<a href="archive-h60-cotrain-overview.html">H60 co-training</a> ·
<a href="archive-h61-overview.html">H61</a> ·
<a href="archive-h62-overview.html">H62</a> ·
<a href="archive-ctd5-overview.html">CTD5</a> ·
<a href="forensics.html">forensics</a> ·
<a href="feed.html">feed</a> ·
<a href="executive-summary.html">executive summary (H87-era)</a></p>
"""
    page += FOOT
    (DOCS / "index.html").write_text(page)

    # executive summary: prepend the H88 status block (idempotent markers)
    es = DOCS / "executive-summary.html"
    es_text = es.read_text()
    block_start = "<!--H88-EXEC-START-->"
    block_end = "<!--H88-EXEC-END-->"
    submit_line = ("SUBMIT OK — promote rule passed." if submit_ok else
                   "DO NOT SUBMIT — " + card["ok_to_download_and_submit"]["reason"] + ".")
    exec_block = f"""{block_start}
<div class="card" style="border:2px solid var(--accent)">
<h2 style="margin-top:0">H88 — how to make a submission into the contest (current status)</h2>
<p><strong>Current file:</strong> <a href="{rel}">{fname}</a>
(SHA-256 <code>{card['raster']['sha256']}</code>, {card['raster']['ones']:,} positive pixels,
values exactly {{0,1}}, zeros outside the footprint).</p>
<p><strong>Verdict:</strong> {verdict.upper()} — {submit_line}</p>
<ol>
<li>Download the <code>.tif</code> (or <code>.zip</code>) from the <a href="index.html">front page</a>.</li>
<li>Open the <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/submissions/">DrivenData “New submission” form</a> (login required).</li>
<li>Under <strong>File to submit</strong>, choose the downloaded <code>.tif</code> (or the zip). It must match the
submission format's CRS, shape, and geotransform — ours matches <code>sample_submission.tif</code> byte-for-byte
on the grid. If you ever see “Predicted values must be in range [0, 1]”, the file carried NaNs outside the
footprint; the H88 zeros-outside container cannot produce that error.</li>
<li>Paste the <strong>submission name</strong> <code>{card['submission_name']}</code> and the <strong>note</strong>
<code>{card['submission_note']}</code> (a short comment to tell submissions apart later).</li>
<li>Click Submit. The score appears on the portal; record the receipt as ORGANIZER-CONFIRMED.</li>
</ol>
<p>Every number on this site is HOLDOUT-DTI (local evaluator) or OWNER-REPORTED until such a receipt
exists. NO CERTIFIED LEADERBOARD GAIN is advertised.</p>
</div>
{block_end}"""
    if block_start in es_text:
        i0, i1 = es_text.index(block_start), es_text.index(block_end) + len(block_end)
        es_text = es_text[:i0] + exec_block + es_text[i1:]
    else:
        anchor = '<div class="container">'
        es_text = es_text.replace(anchor, anchor + "\n" + exec_block, 1)
    es.write_text(es_text)

    # round detail page: the full run card rendered
    det = head("GEMSDOE52 — H88 run card")
    det += f"""<h1>H88 run card (all receipts)</h1>
<p><a href="index.html">← back to the download page</a></p>
<pre style="background:var(--card);padding:16px;border-radius:8px;overflow:auto;font-size:0.8rem">{json.dumps(card, indent=1, default=float)}</pre>
"""
    det += FOOT
    (DOCS / "h88.html").write_text(det)
    print(f"published: verdict={verdict} submit={submit_ok} file={fname}")


if __name__ == "__main__":
    main()
