#!/usr/bin/env python3
"""Receipt-driven research pages. No model fitting, selection, or competition upload."""
from __future__ import annotations
import csv
import hashlib
from html import escape as esc
import json
from pathlib import Path
import re
import shutil

ROOT=Path(__file__).resolve().parents[1]
EV=ROOT/'evidence'; DOC=ROOT/'docs'; DATA=DOC/'data'
REPO='https://github.com/buffedlizard55-lab/GEMSDOE52'


def read(name): return json.loads((EV/('ctd5_'+name+'.json')).read_text())

def render(title,body):
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="New geophysical/surface disagreement GeoTIFF with explicit failed scientific and lane gates. Research download only; do not submit.">
<title>{esc(title)} · GEMSDOE52</title><link rel="stylesheet" href="assets/ctd5.css"><script src="assets/ctd5.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a><header><nav aria-label="Main navigation"><a class="brand" href="index.html"><span class="mark" aria-hidden="true">52</span>GEMS / DOE</a>
<a href="index.html">Overview</a><a href="ctd5-audit.html">Run &amp; evidence</a><a href="executive-summary.html">Submission guide</a><a href="ctd5-sources.html">Sources</a><a href="downloads/index.html">Archive</a></nav></header>
<main id="main">{body}</main><footer>Independent competition research, not an official DOE or DrivenData site. Predictions are not verified faults or geothermal discoveries.<br>
<a href="{REPO}">Code &amp; reproducibility</a> · <a href="ctd5-audit.html#limitations">Limitations</a> · <a href="data/ctd5_run_card.json">JSON run card</a> · CTD5 / 2026-10-08</footer></body></html>'''


def metrics_table(results, labels):
    rows=''
    for key,label in labels:
        r=results[key]
        rows+=f'<tr class="{"highlight" if key=="disagreement" else ""}"><td>{esc(label)}</td><td class="numeric">{r["dti"]:.6f}</td><td class="numeric">[{r["ci95"][0]:.6f}, {r["ci95"][1]:.6f}]</td></tr>'
    return '<div class="table-wrap"><table><thead><tr><th>Procedure</th><th>HOLDOUT-DTI</th><th>95% CI</th></tr></thead><tbody>'+rows+'</tbody></table></div>'


def make_preview(card):
    import numpy as np
    import rasterio
    from PIL import Image
    p=ROOT/'work/ctd5/features/valid.npy'
    if not p.exists(): return
    valid=np.load(p)
    scale=600/valid.shape[0];w=int(round(valid.shape[1]*scale));h=600
    mask=np.asarray(Image.fromarray(valid).resize((w,h),Image.Resampling.NEAREST))
    rgb=np.zeros((h,w,3),np.uint8);rgb[:]=(16,47,55);rgb[mask]=(34,70,76)
    with rasterio.open(ROOT/'submission'/card['raster_file']) as ds: a=ds.read(1)>0
    yy,xx=np.nonzero(a);y=np.minimum((yy*scale).astype(int),h-1);x=np.minimum((xx*scale).astype(int),w-1)
    rgb[y,x]=(98,202,165)
    with (EV/card['reasoning']['pixel_csv']).open() as f:
        for r in csv.DictReader(f):
            if r['A_only_candidate_id']:
                y=min(int(int(r['row'])*scale),h-1);x=min(int(int(r['col'])*scale),w-1)
                rgb[y,x]=(241,189,101)
    Image.fromarray(rgb).save(DOC/'assets/ctd5-prediction.png')


def source_claims():
    reference=json.loads((ROOT/'work/ctd5/sources/official-reference-tree.json').read_text()) if (ROOT/'work/ctd5/sources/official-reference-tree.json').exists() else {'sha':'aebe92f7c8a990f0e3443451b7a825d9afd6336b'}
    rows=[
      dict(claim='Official baseline offers CPU and GPU options; GPU is not mandatory for this boosting run.',status='Official GitHub source read this session',url='https://github.com/drivendataorg/gems-prize-reference-solution/blob/'+reference['sha']+'/README.md',evidence='Source blob a8814f99c395d12a8e1c3731c738e61d7dca06b5; actual CTD5 fits ran on CPU.'),
      dict(claim='The target is fault prediction; a raster does not establish a geothermal reservoir.',status='Prior dated official-source audit; not freshly fetched',url='https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/',evidence='evidence/verified_claims_r2.json C01/C02; official reference notebook describes fault detection.'),
      dict(claim='DTI uses the requested 300 m triangular kernel with alpha .2 and beta .8.',status='User specification + prior dated source audit + independently tested local arithmetic',url='https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/',evidence='evidence/verified_claims_r2.json C03; tests/test_metric.py and tests/test_ctd5.py.'),
      dict(claim='Known catalogue pixels are excluded pixel-exactly; off-catalogue flanks are not automatically exempt.',status='Prior dated organizer-staff statement, not a fresh portal retrieval',url='https://community.drivendata.org/t/scoring-clarification-are-known-usgs-ingenious-faults-masked-when-scoring-and-are-they-in-the-final-round-label-set/11516/4',evidence='evidence/verified_claims_r2.json C05/C06.'),
      dict(claim='Co-training assumptions are not established by weak proxy-negative error correlation.',status='Primary-paper link + prior dated literature review; empirical diagnostic measured here',url='https://doi.org/10.1145/279943.279962',evidence='Blum & Mitchell COLT 1998; CTD5 independence and transfer receipts.'),
      dict(claim='GeoDAWN is an official magnetic/radiometric data source; no fresh raw official-host download occurred here.',status='Official source identified; sandbox-host access restricted',url='https://www.usgs.gov/data/geodawn-airborne-magnetic-and-radiometric-surveys-northwestern-great-basin-nevada-and',evidence='DOI 10.5066/P93LGLVQ. Band-6 identity remains disputed; no external radiometric layer trained this run.'),
      dict(claim='Integrated structural/geophysical evidence can motivate blind-system investigations; it does not confirm these candidates.',status='Prior dated official-publication review; hypothesis support only',url='https://www.usgs.gov/publications/discovering-blind-geothermal-systems-great-basin-region-integrated-geologic-and',evidence='DOI 10.2172/1724080; no field validation in CTD5.'),
      dict(claim='INGENIOUS is an official free-data starting point, not independent proof of a proposed fault.',status='Official source identified; raw download and current terms not reverified here',url='https://gdr.openei.org/submissions/1391',evidence='DOI 10.15121/1881483. No external chemistry, fault or vent features used in CTD5.'),
      dict(claim='Competition rules and current allowance must be checked before an independently approved upload.',status='Rules link retained; current submission-page cap/receipt unavailable',url='https://docs.nlr.gov/docs/fy26osti/96647.pdf',evidence='No submission-page receipt, no upload, no slot consumed. Generative-AI assistance disclosed in the research narrative.'),
      dict(claim='Core input files match the manifest pins, not authenticated organizer downloads.',status='Locally verified bytes; organizer provenance unresolved',url=REPO+'/blob/main/registry/data_manifest.json',evidence='evidence/ctd5_input_integrity.json; 23 mirrored inputs restored and SHA-checked.'),
    ]
    (EV/'ctd5_claims.json').write_text(json.dumps(dict(checked_date_utc='2026-10-08',claims=rows),indent=2)+'\n')
    # Preserve the owner/user result list without joining it to a fabricated receipt.
    text=(ROOT/'knowledge/26_current_user_brief.md').read_text().split('The following is the leaderboard for the competition:')[0]
    site=None; seen=set(); reports=[]
    for line in text.splitlines():
        match=re.search(r'https://buffedlizard55-lab.github.io/([^/]+)/',line)
        if match: site=match.group(1)
        m=re.fullmatch(r'([\w.-]+):\s*(0\.\d+)?',line.strip())
        if m and site and (site,m.group(1)) not in seen:
            seen.add((site,m.group(1)))
            reports.append(dict(site=site,submission_label=m.group(1),reported_value=float(m.group(2)) if m.group(2) else None,
                evidence_class='OWNER/USER-REPORTED; NOT ORGANIZER-CONFIRMED',receipt=None,authenticated_file_sha256=None))
    (EV/'ctd5_owner_reported_results.json').write_text(json.dumps(dict(source='knowledge/26_current_user_brief.md',entries=reports,
        warning='Reported associations are not verified scores and are never model inputs or promotion evidence.'),indent=2)+'\n')
    return rows,reports


def main():
    c=read('run_card');pre=read('holdout');post=read('post_holdout');ind=read('independence');canary=read('canary');u=c['correlation_overlap_vs_registry'];r=c['reasoning']
    claims,owner_results=source_claims()
    make_preview(c)
    # Archive the old landing text unchanged except for an explicit archive banner below.
    old=ROOT/'knowledge/archive/README_before_ctd5.md'
    if not old.exists(): shutil.copy2(ROOT/'README.md',old)
    archive=DOC/'archive-h59-overview.html'
    if not archive.exists(): shutil.copy2(DOC/'index.html',archive)
    for p in EV.glob('ctd5_*.json'):
        shutil.copy2(p,DATA/p.name)
    shutil.copy2(ROOT/'registry/ctd5_preregistration.json',DATA/'ctd5_preregistration.json')
    note=f'''<div class="notice" role="note"><strong>OK TO DOWNLOAD FOR RESEARCH · DO NOT SUBMIT</strong><p>The local format check passes. The legacy holdout is not strict-valid, and the scientific comparison and parallel-lane gate do not pass. No competition slot was used. NO CERTIFIED LEADERBOARD GAIN.</p></div>'''
    download=f'''<div class="actions"><a class="button" href="downloads/ctd5-research.tif" download>Download research GeoTIFF ↓</a><a class="button secondary" href="downloads/ctd5-research.zip" download>Single-TIFF ZIP</a></div><p class="fileline">{esc(c['raster_file'])}<br>{c['validator_output']['bytes']:,} bytes · SHA-256 {c['raster_sha256']}</p>'''
    protocol=f'''<p class="small"><b>HOLDOUT-DTI — exploratory legacy-v1, NOT strict holdout-valid</b> · {post['evaluator_version']} · {c['holdout_dti']['withheld_positive_pixels']:,} withheld positives · pooled terms · 300 m triangular kernel · α 0.2 / β 0.8. 95% CI: paired 20 km cluster bootstrap. Not an organizer score.</p>'''
    warning='<p class="small"><b>Validation failure:</b> Legacy evaluation halos depended on withheld fault tails, revealing location to the placement domain. Shared splitter v2 is corrected; no post-stop refit or revised score exists. <a href="data/ctd5_validation_scope_correction.json">Scope correction</a>. <b>Budget-comparison failure:</b> fold 1 emitted only 2,041 of 3,058 requested candidate dots; controls filled their budgets. These are descriptive results, not a valid matched-budget promotion test. The final TIFF contains 12,000 dots.</p>'
    overview=f'''<section class="hero"><div><div class="eyebrow">DOE GEMS / CTD5 research record</div><h1>A new GeoTIFF.<br>A clear stop decision.</h1><p class="lead">Geophysics meets surface evidence. We generated a new disagreement prediction, tested it, and kept the failed gates visible.</p>{note}{download}<p class="small"><a href="executive-summary.html">What exactly can I upload—and when? →</a></p></div>
<aside class="panel" aria-label="Submission readiness"><div class="label">Readiness / measured, not promised</div><div class="status-line"><span>Single-band GeoTIFF</span><span class="good">PASS</span></div><div class="status-line"><span>Finite values in [0, 1]</span><span class="good">PASS</span></div><div class="status-line"><span>CRS, shape &amp; transform</span><span class="good">PASS</span></div><div class="status-line"><span>Copied prior prediction?</span><span class="good">NO</span></div><div class="status-line"><span>Strict near-dot uniqueness</span><span class="bad">FAIL / STOP</span></div><div class="status-line"><span>Scientific promotion</span><span class="bad">NOT APPROVED</span></div><p class="fine">A valid file is not an approved competition entry. The independent selector has not assigned a slot.</p><a class="small" href="data/ctd5_run_card.json">Inspect the complete JSON run card ↗</a></aside></section>
<hr class="divider"><div class="section-head"><h2>What the holdout actually says</h2><a href="ctd5-audit.html">Read the method &amp; limitations →</a></div>{protocol}{warning}
{metrics_table(post['scores'],[('single_B','Surface-only control'),('pre_exchange','Disagreement before transfer'),('disagreement','Disagreement after one exchange')])}
<hr class="divider"><div class="cards"><section class="card"><div class="eyebrow">01 / newly inferred</div><h3>No inherited prediction core</h3><span class="num">0 copied priors</span><p>Prior rasters enter only the audit. The new file is not a renamed prior, not a retained “credited core,” and not the union of the two views.</p></section><section class="card"><div class="eyebrow">02 / scope disclosed</div><h3>The lane rule stopped the run</h3><span class="num">{u['priors_checked']} rasters checked</span><p>A survey-wide lattice is within three pixels of every eligible cell. The literal overlap gate fails even though no decoded prediction is identical.</p></section><section class="card"><div class="eyebrow">03 / review, not discovery</div><h3>Geology for every A-only segment</h3><span class="num">{r['a_only_segments']:,} review records</span><p>Measured context, a named non-fault mimic and a falsifier—not invented field observations. All {r['emitted_reasoning_rows']:,} emitted cells have a record too.</p></section></div>
<hr class="divider"><div class="grid2"><section><div class="eyebrow">The H33 question</div><h2>Better placement is plausible.<br>A higher score is not proven.</h2><p>Re-reading the files shows H33 removed 2,545 off-catalogue flank dots from its immediate parent and added none. This can reduce false-positive mass, but hidden credit is unknown.</p><p class="small">The supplied <b>0.2778</b> association is <b>OWNER-REPORTED, NOT ORGANIZER-CONFIRMED</b>. GEMSDOE32’s source instead says “NO ORGANISER SCORE EXISTS.” We did not turn that conflict into a score claim.</p><a href="ctd5-audit.html#h33">The exact evidence and metric argument →</a></section><figure style="margin:0"><img class="map" src="assets/ctd5-prediction.png" width="530" height="600" alt="Unverified CTD5 predictions over the eligible raster footprint; no geographic feature is asserted to be a verified fault."><figcaption class="legend"><span><i class="swatch"></i>Emitted predictions</span><span><i class="swatch amber"></i>Strict A-only subset</span></figcaption><p class="fine">Actual raster preview, north up. Enlarged display pixels; not a verified fault or geothermal-resource map.</p></figure></div>
<div class="feed" id="local-feed">Automatic local evidence checks. Submission gate: CLOSED. Organizer results are not a live feed.</div>'''
    h58=json.loads((DATA/'h58_result.json').read_text())['artifact']
    h57=json.loads((DATA/'submission_h57_creditcore.json').read_text())
    history=f'''<details><summary>Preserved research archives — do not upload</summary><p class="small">None of these historical files is current approval. H58: <a href="downloads/h58-candidate.tif" download>{h58['file']}</a>, SHA-256 <code>{h58['sha256'][:24]}</code>…; research only, not approved to submit. <a href="h58.html">H58 negative-result audit</a>.</p><p class="small"><a href="downloads/{h57['file']}" download>{h57['file']}</a> is the unapproved H57 alternate; <a href="h57-creditcore.html">historical audit</a>. <a href="h55-edge.html">H55-EDGE negative-result archive</a> · <a href="archive-h59-overview.html">Former H59 landing page, historical claims superseded</a>.</p></details>'''
    history += '<p class="small">Concurrent H60 co-training result: <a href="h60.html">audit</a> · <a href="downloads/h60-cotrain-candidate.tif" download>research-only TIFF</a>. The separate <a href="h60-triple-convergence.html">H60 triple-convergence archive</a> is also preserved. Neither is approval.</p>' if (DOC/'h60-triple-convergence.html').exists() else ''
    parallel=''
    if (EV/'ctd5_parallel_reconciliation.json').exists():
        parallel='<p class="small">Concurrent closure: the later H60 artifact was checked separately against unchanged CTD5 predictions. Initial closure: 542 files / 361 patterns; a second concurrent H60 then brought the total to 543 files / 362 patterns. The original duplicate STOP remains. <a href="data/ctd5_parallel_reconciliation.json">First supplemental audit</a> · <a href="data/ctd5_second_parallel_check.json">Second supplemental audit</a>. The inherited H60 pointer is unapproved, not selected by this session. <a href="h60.html">Preserved H60 archive</a>.</p>'
    (DOC/'index.html').write_text(render('Research download & explicit submission status',overview+parallel+history))
    guide=f'''<div class="eyebrow">Executive summary / submission guide</div><h1>Download now.<br>Do not upload this run.</h1><p class="lead">A single file, an exact identifier, and a separate scientific approval decision. This run is a negative result—not a competition-slot recommendation.</p>{note}{download}
<div class="grid2"><section class="panel"><h2>The file contract</h2><ul><li>One band, float32, values exactly 0 or 1.</li><li>No NaN or infinity anywhere; zero outside the footprint.</li><li>EPSG:32611; 3,730 rows × 3,292 columns.</li><li>Affine [100, 0, 243350, 0, -100, 4508550], identical to the pinned sample.</li><li>The ZIP contains only one TIFF, byte-identical to the direct download.</li></ul><p class="small">Verified locally against the mirror template. This is not an organizer acceptance receipt.</p></section><section class="panel"><h2>Why upload is blocked</h2><ul><li>The strict three-pixel overlap gate failed.</li><li>Legacy held-tail-informed evaluation geometry invalidates strict holdout evidence.</li><li>A holdout fold could not fill the fixed budget.</li><li>No matched-budget improvement over the current best has been established.</li><li>Input provenance and the current weekly allowance are not organizer-authenticated.</li></ul><a href="ctd5-audit.html">Read the negative result →</a></section></div>
<section class="prose"><h2>About “Predicted values must be in range [0, 1]”</h2><p>The new exporter refuses non-finite values and values outside the range, then reopens and validates the written TIFF. It also checks the template grid. We do <b>not</b> claim that NaNs caused your specific historical rejection: the rejected bytes and portal receipt were not available. All-finite export is a compatibility precaution, not proof about the portal’s internals.</p>
<h2>Exact competition steps—only for a future approved candidate</h2><ol><li>First obtain a separate selector’s approval after all scientific, provenance, uniqueness and current-best gates pass. <b>CTD5 does not pass; stop here for this file.</b></li><li>Review the <a href="https://docs.nlr.gov/docs/fy26osti/96647.pdf">official rules</a> and the remaining weekly allowance displayed on your authenticated submission page. This site cannot verify that allowance.</li><li>On the <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/">competition page</a>, choose New submission. Select the approved <code>.tif</code>, or its ZIP containing one TIFF, in <b>File to submit</b>. Do not upload HTML, a JSON receipt, a screenshot, or this executive summary.</li><li>Use the exact audited filename and identifying note. Do not reproject, stretch pixel values, or let an image editor rewrite the TIFF.</li><li>After a successful authorized upload, preserve the submission ID, timestamp, file SHA-256 and organizer result receipt. Only that receipt can support an <b>ORGANIZER-CONFIRMED</b> score.</li></ol></section>
<h2>Identification for this research artifact</h2><p class="small">These fields identify the download; copying them is not permission to upload it.</p><label for="submission-name">Unique name</label><input id="submission-name" readonly value="{esc(c['submission_name'],quote=True)}"><div class="copy-row"><button class="copy" data-copy-id="submission-name">Copy name</button></div><label for="submission-note">Note · {len(c['note'])} / 140 characters</label><textarea id="submission-note" readonly rows="3">{esc(c['note'])}</textarea><div class="copy-row"><button class="copy" data-copy-id="submission-note">Copy note</button></div><p class="copy-status" id="copy-status" aria-live="polite"></p>
<h2>How the site generates a file</h2><p>This reproduction intentionally preserves the rejected legacy-v1 assay and cannot establish promotion-valid performance. For a new experiment use the corrected shared v2 splitter and a new registration. The CPU pipeline restores pinned inputs, reuses the template feature builder, fits both views, runs the canary and blocked evaluation, and writes the checked GeoTIFF. GitHub Pages is static: it serves the generated file, it does not pretend to train inside your browser.</p><div class="actions"><a class="button secondary" href="{REPO}/actions/workflows/reproduce-ctd5.yml">Reproduce research in GitHub Actions ↗</a><a class="button secondary" href="{REPO}/blob/main/scripts/reproduce_ctd5.sh">Inspect the one-command pipeline</a></div><p class="small">Reproduction generates the same negative research result. The workflow never uploads to DrivenData, never promotes a candidate, and never spends a slot. Starting an Actions reproduction requires repository access; the downloadable file above is already built.</p><pre class="code">python -m venv .venv
.venv/bin/pip install -r requirements-r2.txt
GEMS_PYTHON=.venv/bin/python bash scripts/reproduce_ctd5.sh</pre>'''
    (DOC/'executive-summary.html').write_text(render('Executive summary & conditional submission steps',guide+history))
    folds=''.join(f'<tr><td>{f["fold"]}</td><td>{f["target_budget"]:,}</td><td>{f["emitted"]:,}</td><td>{"complete" if f["budget_complete"] else "FAIL: support shortfall"}</td></tr>' for f in post['folds'])
    audit=f'''<div class="eyebrow">CTD5 / scientific audit</div><h1>One hypothesis.<br>One exchange. No promotion.</h1>{note}<p class="lead">Cover-matched geophysical confidence, with surface abstention as the discovery signal. Negative results are part of the deliverable.</p>
<section class="prose"><h2>Registered before fitting</h2><p>Four ranked, lane-specific hypotheses are in the <a href="{REPO}/blob/main/knowledge/25_ctd5_preregistered.md">registration document</a>. We tested only cover-matched transfer: equal class weight within training-only basement-depth quartiles, then asymmetric A-confident/B-abstaining ranking. Non-fault basin-fill density boundaries and volcanic lithologic contacts can mimic the mechanism.</p><p>The shared feature cache was missing from the checkout; we rebuilt it once using the existing template builder, not a private feature pipeline. No prior prediction raster or external layer entered a learner. Confidence uses registered training-domain operating ranks, not demonstrated posterior calibration or high precision. The disputed band 6 is provisionally isolated in B, not treated as authenticated radiometric ground truth.</p>
<h2>Leakage and independence checks</h2><p>Original connected fault components were held out whole, with an 80-pixel Euclidean training buffer; transform support is 36 pixels. The visible catalogue is masked pixel-exactly. However, v1 extended evaluation domains using hidden tails; this invalidates strict promotion evidence. The corrected shared v2 split has not been evaluated after STOP. All catalogue-derived sampling constraints use the fold-visible catalogue.</p><p><b>HOLDOUT-DTI diagnostics (not DTI scores):</b> maximum feature-alone AUC {canary['maximum_auc']:.6f}, below the .90 alarm; maximum negative-error correlation {ind['max_abs_correlation']:.6f} across {ind['n_blocks']:,} blocks, below the .60 stop threshold. Catalogue-zero negatives are not verified fault absence. Neither screen proves conditional independence or sufficient views.</p><p>One whole-segment confident-to-abstaining exchange was run, with training-only pseudo-labels and no evaluation overlap. No further hypothesis or parameter search was attempted after the negative result.</p></section>
<h2>Measured performance</h2>{protocol}{warning}{metrics_table(post['scores'],[('single_A','Single A'),('matched_A','Cover-matched A'),('single_B','Single B'),('union','A/B maximum control'),('pre_exchange','Pre-exchange disagreement'),('disagreement','Post-exchange disagreement')])}
<h3 style="margin-top:25px">Attempted versus realized candidate budgets</h3><div class="table-wrap"><table><thead><tr><th>Outer fold</th><th>Requested dots</th><th>Emitted dots</th><th>Budget gate</th></tr></thead><tbody>{folds}</tbody></table></div><p class="small">No post-hoc budget reduction or zero-score filling was used to rescue the method. The CIs describe realized fold outputs and are conditional on this catalogue-based assay, not hidden new-fault truth. The final file is an OOF mosaic: model-boundary seams and inter-fold rank calibration are unvalidated limitations.</p>
<section class="prose"><h2>Not a union—and still a lane duplicate</h2><p>Exact full-footprint rank correlations: surface maximum <b>{u['surface_max_spearman']:.6f}</b>, final-dot maximum <b>{u['final_max_spearman']:.6f}</b>. There are no decoded-identical priors. The asymmetric function is not a rescaled maximum, and the file is not the union of separately placed A/B.</p><p>But the maximum three-pixel directed overlap is <b>{u['final_max_near_3px_fraction']:.0%}</b>, exceeding the registered 70% limit. The <a href="{read('registry_saturation')['prior_source']}">existing spacing-five lattice</a> is within three pixels of <em>every</em> eligible pixel. Under this inclusive registry, no nonempty dot set on this footprint can pass that rule. We logged duplicate/stop, retained the negative artifact, and did not silently exclude the lattice.</p><p><a href="data/ctd5_surface_uniqueness.json">Surface gate</a> · <a href="data/ctd5_dot_uniqueness.json">Final dot gate</a> · <a href="data/ctd5_registry_saturation.json">Independent coverage proof</a> · <a href="data/ctd5_not_union.json">Not-union checks</a></p>
<h2>Geological reasoning for review</h2><p>{r['a_only_segments']:,} connected A-only candidates have native cover, gravity-gradient and slope measurements, a hypothesis, a non-fault mimic and a falsifier. Every one of the {r['emitted_reasoning_rows']:,} emitted pixels also has a row. No measured surface feature is automatically called a road or a fault; no temperature, permeability or field offset is invented.</p><p><a href="downloads/{r['segment_csv']}" download>Download every A-only segment (CSV)</a><br><a href="downloads/{r['pixel_csv']}" download>Download every emitted pixel (CSV)</a></p>
<h2 id="h33">Why did the reported H33 result improve?</h2><p>The supplied <b>0.2778</b> is <b>OWNER-REPORTED / NOT ORGANIZER-CONFIRMED</b>. The <a href="https://github.com/buffedlizard55-lab/GEMSDOE32/blob/0d6a6243147cd63a2000412d575d4c80a36d3a62/docs/index.html">source page</a> currently says no organizer score exists. We did not obtain a receipt that resolves that conflict.</p><p>The files themselves establish a simple operation: 40,199 → 37,654 dots, deleting 2,545 off-catalogue cells within 200 m of the visible catalogue, adding none. Removing low-value mass can improve DTI if reduced false-positive weight outweighs lost maximum-cover credit. Pixel-exact masked known pixels do <b>not</b> incur penalties; these removed flank cells were off that mask.</p><pre class="code">Pruning improves DTI only if:
lost_credit × (1 − 0.2 × old_DTI)
  &lt; 0.2 × old_DTI × removed_FP_mass</pre><p>Without hidden truth and authenticated paired receipts, we cannot recover those terms, prove zero ring credit, infer hidden-label count, or guarantee a better score. CTD5 offers no supported claim of beating the reported result. <a href="data/ctd5_reference_forensics.json">Recomputed set-relation receipt</a>.</p>
<h2 id="limitations">Limitations and next work, in order</h2><ol><li>Resolve universal-coverage registry entries prospectively in the shared selector—or stop before spending another training budget. No private threshold exception.</li><li>Authenticate core input provenance and obtain an organizer score-to-file receipt. A hash match to an owner mirror does not authenticate its upstream source.</li><li>Verify band-6 identity and modeled-layer lineage from official metadata. Remote USGS/GDR/DrivenData hosts were restricted here.</li><li>Pre-register a genuinely support-capacity-feasible comparison. Do not reinterpret this budget-incomparable result as a matched-budget win.</li><li>Use independent geological validation before calling any candidate a fault, much less a geothermal resource.</li></ol><p><b>AI use:</b> an Arena coding assistant wrote and reviewed code, explanatory text and candidate-review templates. No geologist verified these structures and no new field observation was made.</p></section>
<details><summary>Complete reproducibility and review records</summary><ul><li><a href="data/ctd5_run_card.json">Run card + format validator</a></li><li><a href="data/ctd5_preregistration.json">Frozen registration</a></li><li><a href="data/ctd5_canary.json">Every feature-alone canary</a></li><li><a href="data/ctd5_independence.json">OOF negative-error correlation, all blocks</a></li><li><a href="data/ctd5_pseudo_exchange.json">All pseudo-label segments and buffer checks</a></li><li><a href="data/ctd5_post_holdout.json">Pooled DTI + CIs + fold budgets</a></li><li><a href="data/ctd5_input_integrity.json">Real inputs versus quarantined placeholders</a></li><li><a href="{REPO}/blob/main/knowledge/28_ctd5_three_pass_review.md">Three-pass review and remaining issues</a></li></ul></details>'''
    (DOC/'ctd5-audit.html').write_text(render('Method, negative results & audit trail',audit+parallel))
    inventory=read('sources')
    claimrows=''.join(f'<tr><td>{esc(x["claim"])}</td><td>{esc(x["status"])}</td><td><a href="{esc(x["url"],quote=True)}">Review source ↗</a><br>{esc(x["evidence"])}</td></tr>' for x in claims)
    siterows=''
    for x in inventory['sites']:
        pages=x.get('pages',[])
        link=pages[0]['source_url'] if pages else f'https://github.com/{x["repository"]}'
        siterows+=f'<tr><td><a href="{esc(link,quote=True)}">{esc(x["repository"].split("/")[1])}</a></td><td>{esc(x["status"])}</td><td class="numeric">{x.get("prediction_paths",0)}</td><td><code>{esc(x.get("commit", "unavailable"))[:12]}</code></td></tr>'
    sources=f'''<div class="eyebrow">Evidence / source ledger</div><h1>Know what was verified.<br>Know what was not.</h1><p class="lead">Primary-source access, owner claims, local byte checks and scientific interpretation are separate evidence classes.</p>
<div class="notice"><strong>No authenticated organizer score for this artifact</strong><p>Source reads from GitHub are not checks of deployed Pages HTTP. Local research refreshes are not live leaderboard observations. Historical score attributions remain owner/user reports.</p></div>
<h2>Claim-by-claim review</h2><div class="table-wrap"><table class="source-table"><thead><tr><th>Claim / scope</th><th>Verification status</th><th>Source &amp; evidence</th></tr></thead><tbody>{claimrows}</tbody></table></div>
<h2 style="margin-top:35px">All supplied owner sites</h2><p class="small">{len(inventory['sites'])} repository trees read; 526 distinct TIFF blobs, 524 aligned predictions. Source commits are frozen. Unspecified 53GEMSDOE / 54GEMSDOE URLs, private files, release-only artifacts and external storage are not covered.</p><div class="table-wrap"><table><thead><tr><th>Repository source</th><th>Access</th><th>TIFF paths (aliases included)</th><th>Commit</th></tr></thead><tbody>{siterows}</tbody></table></div><p><a href="data/ctd5_sources.json">Page excerpts &amp; immutable source links (JSON)</a> · <a href="data/ctd5_prior_inventory.json">Full raster inventory and aliases (JSON)</a></p>
<h2>Owner-reported results, preserved but not promoted into evidence</h2><p>{len(owner_results)} distinct submission labels from the supplied prompt are preserved with missing scores as null, never zero. None has been joined to an invented organizer receipt or file hash.</p><p><a href="data/ctd5_owner_reported_results.json">Download the complete reported-result list</a> · <a href="{REPO}/blob/main/knowledge/26_current_user_brief.md">Read the complete current user brief</a></p>
<h2>Free official data: what this run actually used</h2><p>Model inputs were only the pinned 19-band core cube. External USGS/GDR layers were restored as part of the inherited manifest but were <b>not</b> used in the learners. Official-host metadata, licensing and raw retrieval were not newly authenticated through this restricted network. Future proposals requiring new raw data remain blocked until obtainability and provenance are checked; no missing layer was invented.</p><p class="small">The official-source summaries inherited from earlier sessions remain dated in <a href="data/verified_claims_r2.json">the prior claims record</a>. They must not be described as fresh official verification.</p>'''
    (DOC/'ctd5-sources.html').write_text(render('Auditable sources & all supplied sites',sources))
    # Historical pages retain their original receipts and content, but never imply current permission.
    for path in DOC.glob('*.html'):
        if path.name in ('index.html','executive-summary.html','ctd5-audit.html','ctd5-sources.html'): continue
        s=path.read_text()
        if '<!--CTD5-ARCHIVE-NOTICE-->' in s: continue
        notice='''<!--CTD5-ARCHIVE-NOTICE--><aside style="padding:14px 22px;background:#fff1de;color:#6e421d;border-bottom:1px solid #dcc8a8;font:14px/1.6 system-ui">Historical research archive, not current upload approval. <a href="index.html" style="color:#126954">Current CTD5 file and failed gates</a>. Older score, provenance and “safe to submit” statements may be superseded; no organizer score is newly confirmed here.</aside>'''
        s=re.sub(r'(<body\b[^>]*>)',lambda m:m.group(1)+notice,s,count=1,flags=re.I)
        path.write_text(s)
    idx=DOC/'downloads/index.html';s=idx.read_text()
    if '<!--CTD5-DOWNLOAD-NOTICE-->' not in s:
        banner='''<!--CTD5-DOWNLOAD-NOTICE--><aside style="padding:20px;background:#fff1de;color:#6e421d;font:16px/1.6 system-ui"><b>Latest research: CTD5 — DO NOT SUBMIT.</b> <a href="ctd5-research.tif" download>Download the new research TIFF</a> · <a href="../executive-summary.html">Read the gate status first</a>. Historical downloads below are not upload approval.</aside>'''
        s=re.sub(r'(<body\b[^>]*>)',lambda m:m.group(1)+banner,s,count=1,flags=re.I);idx.write_text(s)
    (ROOT/'index.html').write_text('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=docs/index.html"><title>GEMSDOE52 — research GeoTIFF and submission status</title></head><body><h1>GEMSDOE52</h1><p><a href="docs/index.html">Open the research download and explicit submission status.</a></p><p>CTD5 is research-only. Do not submit or spend a weekly slot.</p></body></html>''')
    print('CTD5 pages rendered from receipts. Submission remains blocked.')

if __name__=='__main__': main()
