#!/usr/bin/env python3
"""Publish the H101 round from receipts only (evidence/h101_run_card.json and siblings).

Writes ``docs/h101.html`` and ``docs/h101-executive-summary.html`` from scratch, and inserts delimited,
idempotent ``<!--H101-CARD-->`` blocks at the top of the shared landing pages, a ``<!--H101-README-->``
block at the top of README.md and a ``<!--H101-AGENTS-->`` block at the top of AGENTS.md. It never rewrites
a shared page wholesale (historic strings pinned by scripts/check_site.py and tests stay intact).
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
CARD = json.loads((ROOT / "evidence/h101_run_card.json").read_text())
HO = json.loads((ROOT / "evidence/h101_holdout.json").read_text())
RV = json.loads((ROOT / "evidence/h101_reverification.json").read_text())["champion"]
SW = json.loads((ROOT / "evidence/h101_swap_diagnostic.json").read_text())["folds"]
SWAP = "; ".join(f"fold {r['fold']}: removed {r['removed_mean_credit']:.4f} vs added {r['added_mean_credit']:.4f} "
                 f"(n={r['removed']})" for r in SW)
esc = html.escape
SUBMIT_OK = CARD["ok_to_submit"]
DOWNLOAD_OK = CARD["ok_to_download"]
TIFNAME = Path(CARD["raster"]["file"]).name
SHA = CARD["raster"]["sha256"]
NWH = CARD["holdout"]["B_DVA2"]["withheld_positive_px"]
DIS = "https://www.drivendata.org/competitions/306/competition-doe-gems"

ARM_ROLE = {
    "B_DVA2": "control — current holdout best (H82/H84)", "H101_veto": "PRIMARY — fall-line OR road veto of B-only",
    "H101_veto_fl": "attribution — fall-line veto only", "H101_veto_card": "attribution — road (cardinal) veto only",
    "B_DVA2s": "lane-pure View B (surface DVA2 only, IR-H101-001)", "H101_veto_s": "veto on lane-pure View B",
    "H101_consensus": "A as soft prior: r_B·(0.9+0.1·r_A)", "H101_scarp_soft": "contour-parallel prior, no disagreement",
    "single_B": "single-view baseline (surface)", "random": "floor", "single_A": "single-view baseline (geophysics)"}


def f6(x):
    return f"{x:.6f}"


def ci(c):
    return f"[{c[0]:.6f}, {c[1]:.6f}]"


def verdict_text():
    if SUBMIT_OK:
        return "Every frozen gate passed."
    pd = CARD["primary_minus_B_DVA2"]
    return (f"Failed gate(s): {', '.join(CARD['failed_gates'])}. The primary scored HOLDOUT-DTI "
            f"{f6(CARD['holdout']['H101_veto']['dti'])} against the control B_DVA2 "
            f"{f6(CARD['holdout']['B_DVA2']['dti'])}; paired {pd['delta']:+.6f} {ci(pd['ci95'])} — the interval "
            "crosses zero, so it did not beat the current holdout best."
            + (" Its dots are also a lane near-duplicate of this repository's own H84 file (B_DVA2 family; "
               "IR-H101-005), logged as a duplicate." if "lane_dots" in CARD["failed_gates"] else ""))


STYLE = ("<style>body{font:16px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;"
         "max-width:960px;margin:0 auto;padding:20px;color:#14181d;background:#fff}h1{color:#1f4e79;font-size:1.6rem}"
         "h2{color:#1f4e79;border-bottom:1px solid #d0d7de;padding-bottom:4px;margin-top:28px}table{border-collapse:"
         "collapse;width:100%;font-size:.92rem;margin:10px 0}th,td{border-bottom:1px solid #d0d7de;padding:6px 8px;"
         "text-align:left;vertical-align:top}th{background:#f3f7fc}code{background:#eef2f6;padding:1px 4px;"
         "border-radius:3px;font-size:.88em;word-break:break-all}.v{border:3px solid #b42318;border-radius:12px;"
         "padding:14px 18px;background:#fff4f2;margin:14px 0}.v.ok{border-color:#1a7f37;background:#effaf2}"
         ".big{font-size:1.2rem;font-weight:700}.btn{display:inline-block;background:#1f4e79;color:#fff;"
         "padding:10px 18px;border-radius:7px;text-decoration:none;font-weight:700;margin:4px 6px 4px 0}"
         ".btn.g{background:#57606a}.muted{color:#57606a;font-size:.9rem}</style>")


def page(title, body):
    return (f"<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" "
            f"content=\"width=device-width, initial-scale=1\"><title>{esc(title)}</title>{STYLE}</head><body>\n"
            f"{body}\n<p class=\"muted\">Generated by <code>scripts/publish_h101_site.py</code> from "
            "<code>evidence/h101_run_card.json</code>. Every number on this page is copied from a receipt; "
            "HOLDOUT-DTI is a local hide-and-recover measurement, never a leaderboard score. Nothing here is "
            "ORGANIZER-CONFIRMED.</p></body></html>\n")


def verdict_box(prefix=""):
    cls = "v ok" if SUBMIT_OK else "v"
    return (f"<div class=\"{cls}\"><div class=\"big\">OK TO DOWNLOAD: {'YES' if DOWNLOAD_OK else 'NO'} &nbsp;·&nbsp; "
            f"OK TO SUBMIT: {'YES' if SUBMIT_OK else 'NO — research-only, do not upload'}</div>"
            f"<p>{esc(verdict_text())} Weekly submission slots used by this round: <b>0</b>. "
            "Promotion to a real slot is a separate selector step.</p>"
            f"<p><a class=\"btn\" href=\"{prefix}downloads/h101-candidate.tif\" download>Download h101-candidate.tif</a>"
            f"<a class=\"btn g\" href=\"{prefix}downloads/h101-candidate.zip\" download>Single-TIFF ZIP</a>"
            f"<a class=\"btn g\" href=\"{prefix}h101-executive-summary.html\">How to submit</a>"
            f"<a class=\"btn g\" href=\"{prefix}h101.html\">Full result</a></p></div>")


def identity_table():
    v = CARD["validator"]
    rows = [("File", f"<code>{esc(TIFNAME)}</code>"), ("Bytes", f"{CARD['raster']['bytes']:,}"),
            ("SHA-256", f"<code>{SHA}</code>"),
            ("Submission name", f"<code>{esc(CARD['submission']['name'])}</code>"),
            ("Note", f"<code>{esc(CARD['submission']['note'])}</code> ({CARD['submission']['note_chars']}/140 chars)"),
            ("Validator (re-read from disk)",
             f"{v['count']} band {v['dtype']}, {v['crs']}, {v['shape'][0]}×{v['shape'][1]}, CRS/shape/transform/bounds "
             f"match sample_submission.tif: {v['crs_match'] and v['shape_match'] and v['transform_match'] and v['bounds_match']}, "
             f"NaN {v['nan']} (inside footprint {v['nan_inside_footprint']}), inf {v['infinite']}, min {v['min']}, "
             f"max {v['max']}, values {v['values']}, ones {v['ones']:,}, ones outside footprint "
             f"{v['ones_outside_footprint']}, nodata tag {v['nodata']} → <b>{'PASS' if v['PASS'] else 'FAIL'}</b>")]
    return "<table>" + "".join(f"<tr><th>{a}</th><td>{b}</td></tr>" for a, b in rows) + "</table>"


def holdout_table():
    vs = CARD["attribution_minus_B_DVA2"]
    order = sorted(CARD["holdout"], key=lambda a: -CARD["holdout"][a]["dti"])
    out = ["<table><tr><th>arm</th><th>role</th><th>HOLDOUT-DTI</th><th>95 % CI</th><th>arm − B_DVA2 (paired)</th></tr>"]
    for a in order:
        s = CARD["holdout"][a]
        d = "—" if a == "B_DVA2" else (f"{CARD['primary_minus_B_DVA2']['delta']:+.6f} {ci(CARD['primary_minus_B_DVA2']['ci95'])}"
                                       if a == "H101_veto" else f"{vs[a]['delta']:+.6f} {ci(vs[a]['ci95'])}")
        b = "<b>" if a in ("H101_veto", "B_DVA2") else ""
        e = "</b>" if b else ""
        out.append(f"<tr><td>{b}{a}{e}</td><td>{esc(ARM_ROLE.get(a, ''))}</td><td>{b}{f6(s['dti'])}{e}</td>"
                   f"<td>{ci(s['ci95'])}</td><td>{d}</td></tr>")
    out.append("</table>")
    return "".join(out)


def gates_table():
    g = CARD["gates"]
    return "<table><tr><th>frozen gate</th><th>result</th></tr>" + "".join(
        f"<tr><td>{esc(k)}</td><td>{'PASS' if v else '<b>FAIL</b>'}</td></tr>" for k, v in g.items()) + "</table>"


def strata_table():
    rows = ["<table><tr><th>fold</th><th>B-only, fall-line</th><th>B-only, road</th><th>B-only, clean</th>"
            "<th>not B-only</th></tr>"]
    for i, r in enumerate(CARD["control_dot_strata_per_fold"]):
        def c(k):
            x = r[k]
            return f"{x['mean_credit']:.4f} (n={x['n']:,})" if x["mean_credit"] is not None else f"— (n={x['n']})"
        rows.append(f"<tr><td>{i}</td><td>{c('b_only_erosion')}</td><td>{c('b_only_road')}</td>"
                    f"<td>{c('b_only_clean')}</td><td>{c('not_b_only')}</td></tr>")
    rows.append("</table>")
    return "".join(rows)


def how_to_submit(prefix=""):
    return ("<h2>How to submit (exact steps)</h2><ol>"
            f"<li>Download <a href=\"{prefix}downloads/h101-candidate.tif\" download><code>h101-candidate.tif</code></a> "
            f"(or the <a href=\"{prefix}downloads/h101-candidate.zip\" download>ZIP</a>, which holds exactly one GeoTIFF).</li>"
            "<li>Open <a href=\"" + DIS + "/submissions/\">DrivenData → DOE GEMS → Submissions</a> (login required) "
            "and click <i>Submit file</i>.</li>"
            "<li><b>File to submit:</b> choose the .tif (or the .zip). It is a single-band float32 GeoTIFF on the "
            "sample_submission grid (EPSG:32611, 3730 rows × 3292 columns, 100 m), every pixel finite and in [0, 1], "
            "so the portal message <i>\"Predicted values must be in range [0, 1]\"</i> cannot be triggered by NaN or "
            "out-of-range values.</li>"
            f"<li><b>Note (optional):</b> paste <code>{esc(CARD['submission']['note'])}</code>. Keep the file name "
            f"<code>{esc(CARD['submission']['name'])}</code> in your own log so submissions stay distinguishable.</li>"
            "<li>The rules let you pick one submission for scoring at the end; check the weekly cap on the submission "
            "page (<a href=\"" + DIS + "/page/967/\">problem description</a>, "
            "<a href=\"https://docs.nlr.gov/docs/fy26osti/96647.pdf\">NLR/DOE GEMS guidance PDF</a>).</li></ol>"
            + ("" if SUBMIT_OK else "<p class=\"v\"><b>This round's frozen rule says: do not upload this file.</b> "
               "It did not beat the current holdout best. The steps are here so a later promoted file can be "
               "submitted the same way.</p>"))


def full_page():
    c = CARD
    ind = c["independence"]
    lane = c["lane"]
    uq = c["uniqueness"]
    nu = c["not_the_union"]
    bf = c["build_fields"]
    orient = c["orientation_descriptives"]
    body = [
        "<h1>H101 — co-training disagreement as an artefact veto (fall-line / cardinal), 2026-10-10</h1>",
        verdict_box(), "<h2>The file</h2>", identity_table(),
        "<h2>Hypothesis and mechanism</h2>", f"<p>{esc(c['hypothesis'])}</p><p>{esc(c['mechanism'])}</p>",
        "<p>Named non-fault mimics: " + "; ".join(esc(x) for x in c["named_non_fault_mimics"]) + ".</p>",
        f"<h2>Holdout (HOLDOUT-DTI, {esc(HO['evaluator'])}, {NWH:,} withheld positive px, 9,400 dots/fold, 95 % "
        "paired spatial-cluster bootstrap, 1,000 draws)</h2>", holdout_table(),
        f"<p>Controls reproduce: single_B {f6(c['control_reproduction']['single_B']['measured'])} (committed "
        f"{c['control_reproduction']['single_B']['committed']}), B_DVA2 {f6(c['control_reproduction']['B_DVA2']['measured'])} "
        f"(committed {c['control_reproduction']['B_DVA2']['committed']}). Promotion bar {CARD_BAR}.</p>",
        "<h2>What the disagreement stratum actually contains (diagnostic, not a score)</h2>",
        "<p>Mean per-dot kernel credit of the <i>control</i> emission's dots, by stratum (300 m triangle "
        "against the fold's withheld faults):</p>", strata_table(),
        "<p><b>Reading.</b> In every fold the fall-line-flagged B-only dots carry less credit than the clean B-only "
        "dots — the brief's artefact reading is directionally right — but the dots the veto removed still carried more "
        f"credit than the dots that replaced them, in every fold ({esc(SWAP)}; evidence/h101_swap_diagnostic.json). "
        "A hard veto is therefore the wrong operator; "
        "a rank-preserving soft penalty is the next test (needs its own preregistration). Only "
        f"{bf['b_only_erosion_fraction']:.3f} of B-only pool cells are fall-line flagged, below the all-cell base "
        f"rate {orient['fl_ge_erosion_fraction']:.3f}: the surface learner already avoids most drainage lines.</p>",
        "<h2>Co-training obligations</h2><ul>",
        "".join(f"<li>Independence ({esc(k)}): max |ρ| of spatial-block OOF errors on labelled negatives "
                f"{v['max_abs_rho']:.4f} over {v['n_blocks']:,} blocks (abandon at {v['abandon_at']}) → not abandoned.</li>"
                for k, v in ind.items()),
        f"<li>View A sufficiency: mean OOF AUC {c['view_A_sufficiency']['mean']:.4f} → "
        f"{'passes' if c['view_A_sufficiency']['passes'] else 'fails again'}.</li>",
        f"<li>Leakage canary: max single-feature AUC {c['leakage_canary']['max_auc']:.4f} (bar "
        f"{c['leakage_canary']['bar']}); fall-line alignment alone "
        f"{max(c['leakage_canary']['fall_line_alone']):.4f}, cardinal distance alone "
        f"{max(c['leakage_canary']['dcard_alone']):.4f} → no leak.</li>",
        "<li>No pseudo-label exchange (closed negative in H61/H95); the disagreement set is used only as a veto, "
        "so no pseudo-label can reach the evaluation.</li>",
        f"<li>A-only reasoning: {c['a_only_reasoning']['rows']:,} A-only candidates, one row each with measured "
        "View-A z-scores, geological reading, named mimic and falsifier: "
        "<a href=\"downloads/h101-a-only-reasoning.csv\">h101-a-only-reasoning.csv</a>.</li></ul>",
        "<h2>Lane, uniqueness, not-the-union</h2><ul>",
        f"<li>Surface lane (before placement): literal {esc(lane['surface_literal']['verdict'])}, max Spearman "
        f"{lane['surface_literal']['max_spearman']:.4f} over {lane['n_registry']} registry rasters.</li>",
        f"<li>Dot lane (after placement, {esc(str(lane['placement']))}): literal {esc(lane['dots_literal']['verdict'])} "
        f"(max near-3px {lane['dots_literal']['max_near_3px']:.4f} vs <code>{esc(Path(str(lane['dots_literal']['worst'])).name)}</code>); "
        f"policy {esc(lane['dots_policy']['verdict'])} (max near-3px {lane['dots_policy']['max_near_3px']:.4f} vs "
        f"<code>{esc(Path(str(lane['dots_policy']['worst'])).name)}</code>, {lane['dots_policy']['probes_excluded']} "
        "universal-coverage probes excluded).</li>",
        f"<li>Uniqueness: identical to a prior {uq['identical_to_a_prior']}, novel fraction {uq['novel_fraction']:.4f}, "
        f"{uq['n_priors_checked']} priors checked, relation {esc(str(uq['relation_to_union']))}.</li>",
        f"<li>Not the union: Jaccard vs union-max dots {nu['jaccard_with_union']:.4f}, vs single-A "
        f"{nu['jaccard_with_single_A']:.4f}, vs the un-vetoed B_DVA2 dots {nu['jaccard_with_B_DVA2_unvetoed']:.4f}; "
        f"{nu['dots_not_in_union']:,} dots not in the union placement.</li></ul>",
        "<h2>Why h33-2-b2 scored 0.2778, and can we beat it?</h2>",
        "<p>DTI = T / (0.2·S + 0.8·|G|) (Tversky index with α 0.2, β 0.8 — "
        "<a href=\"https://en.wikipedia.org/wiki/Tversky_index\">definition</a>; competition metric page "
        f"<a href=\"{DIS}/page/967/\">967</a>). The champion is the 0.2600 <code>d2-8</code> surface field with every "
        "dot within 200 m of the public catalogue deleted (37,654 binary dots): hidden faults are not in the "
        "catalogue, so those dots were pure false-positive mass. Full derivation from bytes: "
        "<a href=\"../knowledge/76_why_02778_and_what_beating_03195_requires.md\">knowledge/76</a>. Beating 0.3195 needs "
        "≈ 15 % more credit per dot at the same mass. <b>H101 does not deliver that</b>; its honest result is a "
        "negative with a usable lead (soft penalty on fall-line B-only dots).</p>",
        "<h2>Sources for manual review</h2><ul>"
        "<li>Blum &amp; Mitchell, COLT '98, pp. 92–100, <a href=\"https://doi.org/10.1145/279943.279962\">doi:10.1145/279943.279962</a></li>"
        "<li>Wallace (1977) Profiles and ages of young fault scarps, north-central Nevada, GSA Bulletin 88(9):1267–1281, "
        "<a href=\"https://doi.org/10.1130/0016-7606(1977)88%3C1267:PAAOYF%3E2.0.CO;2\">doi:10.1130/0016-7606(1977)88&lt;1267:PAAOYF&gt;2.0.CO;2</a></li>"
        f"<li>Competition: <a href=\"{DIS}/\">overview</a> · <a href=\"{DIS}/page/967/\">problem description</a> · "
        f"<a href=\"{DIS}/leaderboard/\">leaderboard</a> · <a href=\"https://github.com/drivendataorg/gems-prize-reference-solution\">reference solution</a></li>"
        "<li>Preregistration: <a href=\"../knowledge/105_hypotheses_H101_preregistered.md\">knowledge/105</a> · results: "
        "<a href=\"../knowledge/106_h101_results_and_limits.md\">knowledge/106</a> · run card: "
        "<a href=\"../evidence/h101_run_card.json\">evidence/h101_run_card.json</a></li></ul>"]
    return page("GEMSDOE52 · H101 result", "".join(body))


CARD_BAR = "0.190147 (H84 primary); current holdout best B_DVA2 0.192829"


def exec_page():
    body = ["<h1>Executive summary — how to submit to the DOE GEMS competition (H101)</h1>", verdict_box(),
            identity_table(), how_to_submit(),
            "<h2>Troubleshooting the portal</h2><table><tr><th>portal message</th><th>cause</th><th>this file</th></tr>"
            "<tr><td>Predicted values must be in range [0, 1]</td><td>NaN, ±inf or values outside [0, 1] in the raster</td>"
            "<td>0 NaN, 0 inf, values exactly {0, 1}</td></tr>"
            "<tr><td>CRS / shape / geotransform mismatch</td><td>a raster not on the sample_submission grid</td>"
            "<td>EPSG:32611, 3730×3292, transform identical to sample_submission.tif</td></tr>"
            "<tr><td>multi-band file</td><td>more than one band</td><td>1 band, float32</td></tr></table>",
            "<p><a href=\"h101.html\">Full H101 result</a> · <a href=\"index.html\">site home</a></p>"]
    return page("GEMSDOE52 · H101 executive summary / how to submit", "".join(body))


def card_html(prefix):
    s = CARD["holdout"]
    return ("<style>.h101card{border:3px solid #b42318;border-radius:12px;padding:16px 18px;margin:16px 0;background:#fff4f2;"
            "color:#14181d;font:15px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif}"
            ".h101card.ok{border-color:#1a7f37;background:#effaf2}.h101card h2{margin:0 0 8px;font-size:19px;color:#1f4e79}"
            ".h101card a{color:#1f4e79;font-weight:700}.h101card code{background:#eef2f6;padding:1px 4px;border-radius:3px;"
            "font-size:12.5px;word-break:break-all}</style>"
            f"<div class=\"h101card{' ok' if SUBMIT_OK else ''}\"><h2>Latest round H101 (2026-10-10) — co-training "
            "disagreement as a fall-line / cardinal artefact veto</h2>"
            f"<p><b>OK TO DOWNLOAD: {'YES' if DOWNLOAD_OK else 'NO'}</b> (format-valid single-band float32, EPSG:32611, "
            f"3730×3292, all-finite, values exactly {{0,1}}, {CARD['validator']['ones']:,} cells). "
            f"<b>OK TO SUBMIT: {'YES' if SUBMIT_OK else 'NO — research-only, do not upload'}.</b> "
            f"{esc(verdict_text())} Slots used: 0.</p>"
            f"<p><a href=\"{prefix}downloads/h101-candidate.tif\" download>Download h101-candidate.tif</a> · "
            f"<a href=\"{prefix}downloads/h101-candidate.zip\" download>ZIP</a> · "
            f"<a href=\"{prefix}h101-executive-summary.html\">how to submit</a> · <a href=\"{prefix}h101.html\">full result</a></p>"
            f"<p><small><code>{esc(TIFNAME)}</code> · SHA-256 <code>{SHA[:24]}</code> · HOLDOUT-DTI "
            f"(gems52-pooled-hide-v1, {NWH:,} withheld positives): H101_veto {f6(s['H101_veto']['dti'])} vs B_DVA2 "
            f"{f6(s['B_DVA2']['dti'])}; lane-pure surface view B_DVA2s {f6(s['B_DVA2s']['dti'])} (IR-H101-001). "
            "A holdout number is not a board score.</small></p></div>")


def insert_block(path: Path, marker: str, blob: str, *, top_of_body=True):
    text = path.read_text() if path.exists() else "<!doctype html><html><body></body></html>"
    block = f"<!--{marker}-->\n{blob}\n<!--/{marker}-->\n"
    if f"<!--{marker}-->" in text:
        text = re.sub(f"<!--{marker}-->.*?<!--/{marker}-->\n?", lambda m: block, text, flags=re.S)
    elif top_of_body and "<body" in text:
        i = text.find(">", text.find("<body")) + 1
        text = text[:i] + "\n" + block + text[i:]
    else:
        text = block + "\n" + text
    path.write_text(text)


def readme_block():
    s = CARD["holdout"]
    pd = CARD["primary_minus_B_DVA2"]
    v = CARD["validator"]
    lane = CARD["lane"]
    rows = "\n".join(f"| `{a}` | {ARM_ROLE.get(a, '')} | {f6(s[a]['dti'])} {ci(s[a]['ci95'])} |"
                     for a in sorted(s, key=lambda a: -s[a]["dti"]))
    gates = "\n".join(f"| {k} | {'PASS' if g else '**FAIL**'} |" for k, g in CARD["gates"].items())
    return f"""<!--H101-README-->
# Current status — H101 (2026-10-10): co-training disagreement as an artefact veto · NEGATIVE

> **OK TO DOWNLOAD: {'YES' if DOWNLOAD_OK else 'NO'}** — format-valid single-band float32 GeoTIFF, EPSG:32611, 3730×3292,
> all-finite, values exactly {{0,1}} (the portal's *"Predicted values must be in range [0, 1]"* rejection cannot occur).
>
> **OK TO SUBMIT: {'YES' if SUBMIT_OK else 'NO — research-only, do not upload.'}** {verdict_text()}
>
> Weekly slots used: **0**. The agent does not pick submissions; promotion is a separate selector step.

**★ [Download h101-candidate.tif](docs/downloads/h101-candidate.tif)** · [ZIP](docs/downloads/h101-candidate.zip) ·
**[Executive summary / how to submit](docs/h101-executive-summary.html)** · [Full result](docs/h101.html) ·
[Run card](evidence/h101_run_card.json) · [A-only reasoning CSV](docs/downloads/h101-a-only-reasoning.csv)

- **File:** `{CARD['raster']['file']}` — {CARD['raster']['bytes']:,} bytes, SHA-256 `{SHA}`
- **Submission name:** `{CARD['submission']['name']}` · **Note ({CARD['submission']['note_chars']}/140):** `{CARD['submission']['note']}`
- **Validator (re-read from disk):** {v['count']} band {v['dtype']}, {v['crs']}, {v['shape'][0]}×{v['shape'][1]}, CRS/shape/transform/bounds = sample_submission.tif: {v['crs_match'] and v['shape_match'] and v['transform_match'] and v['bounds_match']}, NaN {v['nan']}, inf {v['infinite']}, values {v['values']}, {v['ones']:,} ones, 0 outside footprint → {'PASS' if v['PASS'] else 'FAIL'}
- **HOLDOUT-DTI** (`gems52-pooled-hide-v1`, {NWH:,} withheld positive px, 9,400 dots/fold, 95 % paired cluster bootstrap):

| arm | role | HOLDOUT-DTI [95 % CI] |
|---|---|---|
{rows}

  Primary − control `B_DVA2` = **{pd['delta']:+.6f}** {ci(pd['ci95'])} → does not beat the holdout best.
- **Independence:** max |ρ| {', '.join(f"{v2['max_abs_rho']:.4f} ({k})" for k, v2 in CARD['independence'].items())}; abandon ≥ 0.60 → not abandoned. View A sufficiency mean AUC {CARD['view_A_sufficiency']['mean']:.4f} (fails again).
- **Leakage canary:** max single-feature AUC {CARD['leakage_canary']['max_auc']:.4f} (bar 0.90) → none.
- **Lane:** surface {lane['surface_literal']['verdict']} (max ρ {lane['surface_literal']['max_spearman']:.4f}); dots literal {lane['dots_literal']['verdict']} (max near-3px {lane['dots_literal']['max_near_3px']:.4f}), policy {lane['dots_policy']['verdict']} (max near-3px {lane['dots_policy']['max_near_3px']:.4f}).
- **Gates (frozen in `registry/h101_preregistration.json`):**

| gate | result |
|---|---|
{gates}

- **New finding (IR-H101-001):** the holdout-best "View B" `B_DVA2` contains gravity/basement variogram channels (bands 13/15/18). The lane-pure surface view `B_DVA2s` scores {f6(s['B_DVA2s']['dti'])}, i.e. {s['B_DVA2s']['dti'] - s['B_DVA2']['dti']:+.6f} — the View-A physics inside "B" is worth ≈ 0.008 HOLDOUT-DTI.
- **Lead (not evidence of a gain):** fall-line-flagged B-only dots carry less credit than clean B-only dots in all four folds, but the removed dots still out-credit their replacements in all four folds ({SWAP}) — test a rank-preserving soft penalty next.
- **Why `h33-2-b2` scored 0.2778 / can we beat 0.3195?** It is the 0.2600 `d2-8` surface field with every dot ≤ 200 m from the public catalogue deleted (re-verified from bytes this session, `evidence/h101_reverification.json`: {RV['dots']:,} dots, values {{0,1}}, nearest dot {RV['min_dist_to_labels_m']} m from `labels.tif`, median {RV['median_dist_m']} m, {RV['pct_within_300m']} % within 300 m); DTI = T/(0.2·S + 0.8·|G|) rewards removing dots that cannot hit *new* faults. Beating 0.3195 needs ≈ 15 % more credit per dot at the same mass ([knowledge/76](knowledge/76_why_02778_and_what_beating_03195_requires.md)); note 0.3195 is rank 8 and the board top is 0.3774 (re-observed live this session, `evidence/h101_reverification.json`; IR-H85-008), which needs ≈ ×1.36 the champion's credit density. H101 does not deliver it; nothing in this repository has yet demonstrated it.
- **Candidate hypotheses (5, ranked by expected gain ÷ cost, with layers, signature, why off-catalogue, how new):** [knowledge/105 §1](knowledge/105_hypotheses_H101_preregistered.md). The top one was run; #5 (INGENIOUS temperature probes, GDR 1391) needs an owner download: gdr.openei.org returned no connection from this sandbox (curl code 000, `evidence/h101_reverification.json`).
- Docs: [preregistration](knowledge/105_hypotheses_H101_preregistered.md) · [results & limits](knowledge/106_h101_results_and_limits.md) · [irregularities](registry/irregularities.json)
- Reproduce: `python3 scripts/restore_data.py --target-dir data` → `PYTHONPATH=src python -c "from gems52 import structural; structural.build(dest='work/r2/features', include_optional_profiles=False)"` → `PYTHONPATH=src python -m gems52.external` → `python scripts/fetch_prior_inventory.py --out work/h61/priors --receipt work/h61/prior_fetch_receipt.json` → `python scripts/run_h101.py all` → `python scripts/h101_card.py` → `python scripts/publish_h101_site.py && python scripts/check_site.py`.
- The standing brief for this session is the same text as `knowledge/94_current_user_brief_2026-10-10_H95.md` (reproduced verbatim in the H95 block below); read it every session.

<!--/H101-README-->

"""


def agents_block():
    s = CARD["holdout"]
    return f"""<!--H101-AGENTS-->
## Current H101 continuation (2026-10-10) — READ FIRST
Read README's H101 block, `knowledge/105` (frozen preregistration, SHA-256 `{CARD['preregistration']['sha256'][:16]}…`) and
`knowledge/106` (results). Verdict **{CARD['verdict'].upper()}**: download yes (audit only), submit **{'YES' if SUBMIT_OK else 'NO'}**. Experiments 3 of 3, slots 0.

- The B-only stratum as a hard artefact veto does not beat `B_DVA2` (H101_veto {f6(s['H101_veto']['dti'])} vs {f6(s['B_DVA2']['dti'])}, CI spans 0).
  Fall-line-flagged B-only dots are worse than clean B-only dots in 4/4 folds but removed dots beat their replacements 4/4:
  next test is a rank-preserving soft penalty (new preregistration required).
- **IR-H101-001:** `B_DVA2` (holdout best) is not a pure surface view: it includes DVA2 of bands 13/15/18. Lane-pure
  `B_DVA2s` = {f6(s['B_DVA2s']['dti'])}. Report both in any co-training round.
- Consensus (A as soft prior) and the contour-parallel prior without disagreement both lose to `B_DVA2`.
- Reuse `scripts/run_h101.py` stages; it redirects run_h84/run_h82 checkpoints to `work/h101` (no forks).
<!--/H101-AGENTS-->
"""


def main():
    (DOCS / "h101.html").write_text(full_page())
    (DOCS / "h101-executive-summary.html").write_text(exec_page())
    insert_block(DOCS / "index.html", "H101-CARD", card_html(""))
    insert_block(DOCS / "executive-summary.html", "H101-CARD", card_html(""))
    insert_block(ROOT / "index.html", "H101-CARD", card_html("docs/"))
    dl = DOCS / "downloads" / "index.html"
    if dl.exists():
        insert_block(dl, "H101-CARD", card_html("../").replace("../downloads/", ""))
    for path, marker, blob in ((ROOT / "README.md", "H101-README", readme_block()),
                               (ROOT / "AGENTS.md", "H101-AGENTS", agents_block())):
        t = path.read_text()
        if f"<!--{marker}-->" in t:
            t = re.sub(f"<!--{marker}-->.*?<!--/{marker}-->\n*", lambda m: blob, t, flags=re.S)
        else:
            t = blob + t
        path.write_text(t)
    print("published H101:", CARD["verdict"], "submit_ok", SUBMIT_OK)


if __name__ == "__main__":
    main()
